// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approverEligible = `-- name: ApproverEligible :one
select exists (
    select 1
    from public.users u
    where u.id = $1 and u.status = 'active'
      and exists (
          select 1
          from public.organization_memberships m
          join public.roles r on r.id = m.role_id and r.deleted_at is null
          join public.role_permissions rp on rp.role_id = m.role_id
          where m.organization_id = $2
            and m.user_id = $1
            and rp.permission_key = $3
      )
) as eligible
`

type ApproverEligibleParams struct {
	ApproverID     pgtype.UUID
	OrganizationID pgtype.UUID
	PermissionKey  string
}

// Recheck active status and the action’s live permission inside the decision transaction; see LockApproverMembership for the revocation-lock boundary.
func (q *Queries) ApproverEligible(ctx context.Context, arg ApproverEligibleParams) (bool, error) {
	row := q.db.QueryRow(ctx, approverEligible, arg.ApproverID, arg.OrganizationID, arg.PermissionKey)
	var eligible bool
	err := row.Scan(&eligible)
	return eligible, err
}

const cancelDraftsForConnection = `-- name: CancelDraftsForConnection :many
update public.access_requests
set state = 'cancelled', state_reason = 'connection_archived', version = version + 1,
    updated_at = $1::timestamptz
where connection_id = $2 and organization_id = $3
  and state = 'draft'
returning id, organization_id, connection_id, requester_id, state, state_reason, payload_key_version, payload_wrapped_dek, payload_nonce, payload_ciphertext, payload_digest, payload_digest_key_version, redacted_sql, statement_class, policy_version, required_approvals, submitted_at, connection_config_version, connection_fingerprint, connection_display_name, connection_db_type, expires_at, version, created_at, updated_at, title
`

type CancelDraftsForConnectionParams struct {
	At             pgtype.Timestamptz
	ConnectionID   pgtype.UUID
	OrganizationID pgtype.UUID
}

// Archive sweeps drafts to cancelled (§4.3: draft → cancelled on archive), on the same observed instant as the expiry above.
func (q *Queries) CancelDraftsForConnection(ctx context.Context, arg CancelDraftsForConnectionParams) ([]AccessRequest, error) {
	rows, err := q.db.Query(ctx, cancelDraftsForConnection, arg.At, arg.ConnectionID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessRequest{}
	for rows.Next() {
		var i AccessRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ConnectionID,
			&i.RequesterID,
			&i.State,
			&i.StateReason,
			&i.PayloadKeyVersion,
			&i.PayloadWrappedDek,
			&i.PayloadNonce,
			&i.PayloadCiphertext,
			&i.PayloadDigest,
			&i.PayloadDigestKeyVersion,
			&i.RedactedSql,
			&i.StatementClass,
			&i.PolicyVersion,
			&i.RequiredApprovals,
			&i.SubmittedAt,
			&i.ConnectionConfigVersion,
			&i.ConnectionFingerprint,
			&i.ConnectionDisplayName,
			&i.ConnectionDbType,
			&i.ExpiresAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAccessRequests = `-- name: CountAccessRequests :one
select count(*) from public.access_requests r
where r.organization_id = $1
  and ($2::text is null
       or (case when r.state = 'approved' and (r.expires_at is null or r.expires_at <= now()) then 'expired' else r.state end) = $2)
  and ($3::uuid is null or r.requester_id = $3)
`

type CountAccessRequestsParams struct {
	OrganizationID pgtype.UUID
	State          *string
	RequesterID    pgtype.UUID
}

// Counts on the EFFECTIVE state too, so the total matches the filtered rows.
func (q *Queries) CountAccessRequests(ctx context.Context, arg CountAccessRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccessRequests, arg.OrganizationID, arg.State, arg.RequesterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countValidApprovals = `-- name: CountValidApprovals :one
select count(*) from public.approvals a
join public.users u on u.id = a.approver_id and u.status = 'active'
where a.request_id = $1
  and a.organization_id = $2
  and a.decision = 'approved'
  and a.approver_id <> $3
  and exists (
      select 1
      from public.organization_memberships m
      join public.roles r on r.id = m.role_id and r.deleted_at is null
      join public.role_permissions rp on rp.role_id = m.role_id
      where m.organization_id = a.organization_id
        and m.user_id = a.approver_id
        and rp.permission_key = 'requests.approve'
  )
`

type CountValidApprovalsParams struct {
	RequestID      pgtype.UUID
	OrganizationID pgtype.UUID
	RequesterID    pgtype.UUID
}

// How many recorded approvals still COUNT (ADR-0018): the approver is active, still resolves requests.approve through the live membership→role→permission join (the PermissionsForUser shape, rbac.sql), and is not the requester.
func (q *Queries) CountValidApprovals(ctx context.Context, arg CountValidApprovalsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countValidApprovals, arg.RequestID, arg.OrganizationID, arg.RequesterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const existsExecutingForConnection = `-- name: ExistsExecutingForConnection :one
select exists (
    select 1 from public.access_requests
    where connection_id = $1 and organization_id = $2
      and state = 'executing'
) as executing
`

type ExistsExecutingForConnectionParams struct {
	ConnectionID   pgtype.UUID
	OrganizationID pgtype.UUID
}

// The archive guard (§4.3): refuse while an execution is in flight. The state is unreachable until the execution slice; the guard is inherited (ADR-0018).
func (q *Queries) ExistsExecutingForConnection(ctx context.Context, arg ExistsExecutingForConnectionParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsExecutingForConnection, arg.ConnectionID, arg.OrganizationID)
	var executing bool
	err := row.Scan(&executing)
	return executing, err
}

const expireLiveRequestsForConnection = `-- name: ExpireLiveRequestsForConnection :many
update public.access_requests
set state = 'expired', state_reason = $1, version = version + 1,
    updated_at = $2::timestamptz
where connection_id = $3 and organization_id = $4
  and state in ('pending', 'approved')
returning id, organization_id, connection_id, requester_id, state, state_reason, payload_key_version, payload_wrapped_dek, payload_nonce, payload_ciphertext, payload_digest, payload_digest_key_version, redacted_sql, statement_class, policy_version, required_approvals, submitted_at, connection_config_version, connection_fingerprint, connection_display_name, connection_db_type, expires_at, version, created_at, updated_at, title
`

type ExpireLiveRequestsForConnectionParams struct {
	StateReason    *string
	At             pgtype.Timestamptz
	ConnectionID   pgtype.UUID
	OrganizationID pgtype.UUID
}

// Expire pending/approved requests and append derived audit events in the policy/archive transaction, using the post-lock observed instant (ADR-0018).
func (q *Queries) ExpireLiveRequestsForConnection(ctx context.Context, arg ExpireLiveRequestsForConnectionParams) ([]AccessRequest, error) {
	rows, err := q.db.Query(ctx, expireLiveRequestsForConnection,
		arg.StateReason,
		arg.At,
		arg.ConnectionID,
		arg.OrganizationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessRequest{}
	for rows.Next() {
		var i AccessRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ConnectionID,
			&i.RequesterID,
			&i.State,
			&i.StateReason,
			&i.PayloadKeyVersion,
			&i.PayloadWrappedDek,
			&i.PayloadNonce,
			&i.PayloadCiphertext,
			&i.PayloadDigest,
			&i.PayloadDigestKeyVersion,
			&i.RedactedSql,
			&i.StatementClass,
			&i.PolicyVersion,
			&i.RequiredApprovals,
			&i.SubmittedAt,
			&i.ConnectionConfigVersion,
			&i.ConnectionFingerprint,
			&i.ConnectionDisplayName,
			&i.ConnectionDbType,
			&i.ExpiresAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireOverdueAccessRequest = `-- name: ExpireOverdueAccessRequest :many
with observed as materialized (select clock_timestamp() as at)
update public.access_requests
set state = 'expired', state_reason = 'ttl_expired', version = version + 1,
    updated_at = (select at from observed)
where id = $1 and organization_id = $2
  -- The window closes exactly at expires_at (access.Request.ApprovalExpiredAt, ADR-0018).
  and state = 'approved' and (expires_at is null or expires_at <= (select at from observed))
returning id, organization_id, connection_id, requester_id, state, state_reason, payload_key_version, payload_wrapped_dek, payload_nonce, payload_ciphertext, payload_digest, payload_digest_key_version, redacted_sql, statement_class, policy_version, required_approvals, submitted_at, connection_config_version, connection_fingerprint, connection_display_name, connection_db_type, expires_at, version, created_at, updated_at, title
`

type ExpireOverdueAccessRequestParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

// Use one materialized clock_timestamp() for expiry predicate and updated_at after locking. The returned instant also dates derived audit evidence (ADR-0018).
func (q *Queries) ExpireOverdueAccessRequest(ctx context.Context, arg ExpireOverdueAccessRequestParams) ([]AccessRequest, error) {
	rows, err := q.db.Query(ctx, expireOverdueAccessRequest, arg.ID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessRequest{}
	for rows.Next() {
		var i AccessRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ConnectionID,
			&i.RequesterID,
			&i.State,
			&i.StateReason,
			&i.PayloadKeyVersion,
			&i.PayloadWrappedDek,
			&i.PayloadNonce,
			&i.PayloadCiphertext,
			&i.PayloadDigest,
			&i.PayloadDigestKeyVersion,
			&i.RedactedSql,
			&i.StatementClass,
			&i.PolicyVersion,
			&i.RequiredApprovals,
			&i.SubmittedAt,
			&i.ConnectionConfigVersion,
			&i.ConnectionFingerprint,
			&i.ConnectionDisplayName,
			&i.ConnectionDbType,
			&i.ExpiresAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccessRequest = `-- name: GetAccessRequest :one
select id, organization_id, connection_id, requester_id, state, state_reason, payload_key_version, payload_wrapped_dek, payload_nonce, payload_ciphertext, payload_digest, payload_digest_key_version, redacted_sql, statement_class, policy_version, required_approvals, submitted_at, connection_config_version, connection_fingerprint, connection_display_name, connection_db_type, expires_at, version, created_at, updated_at, title from public.access_requests
where id = $1 and organization_id = $2
`

type GetAccessRequestParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) GetAccessRequest(ctx context.Context, arg GetAccessRequestParams) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, getAccessRequest, arg.ID, arg.OrganizationID)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ConnectionID,
		&i.RequesterID,
		&i.State,
		&i.StateReason,
		&i.PayloadKeyVersion,
		&i.PayloadWrappedDek,
		&i.PayloadNonce,
		&i.PayloadCiphertext,
		&i.PayloadDigest,
		&i.PayloadDigestKeyVersion,
		&i.RedactedSql,
		&i.StatementClass,
		&i.PolicyVersion,
		&i.RequiredApprovals,
		&i.SubmittedAt,
		&i.ConnectionConfigVersion,
		&i.ConnectionFingerprint,
		&i.ConnectionDisplayName,
		&i.ConnectionDbType,
		&i.ExpiresAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
	)
	return i, err
}

const getAccessRequestForUpdate = `-- name: GetAccessRequestForUpdate :one
select id, organization_id, connection_id, requester_id, state, state_reason, payload_key_version, payload_wrapped_dek, payload_nonce, payload_ciphertext, payload_digest, payload_digest_key_version, redacted_sql, statement_class, policy_version, required_approvals, submitted_at, connection_config_version, connection_fingerprint, connection_display_name, connection_db_type, expires_at, version, created_at, updated_at, title from public.access_requests
where id = $1 and organization_id = $2
for update
`

type GetAccessRequestForUpdateParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

// The row lock every decision path takes first: concurrent approvals then serialize, so the quorum count and its transition are race-free (ADR-0018).
func (q *Queries) GetAccessRequestForUpdate(ctx context.Context, arg GetAccessRequestForUpdateParams) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, getAccessRequestForUpdate, arg.ID, arg.OrganizationID)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ConnectionID,
		&i.RequesterID,
		&i.State,
		&i.StateReason,
		&i.PayloadKeyVersion,
		&i.PayloadWrappedDek,
		&i.PayloadNonce,
		&i.PayloadCiphertext,
		&i.PayloadDigest,
		&i.PayloadDigestKeyVersion,
		&i.RedactedSql,
		&i.StatementClass,
		&i.PolicyVersion,
		&i.RequiredApprovals,
		&i.SubmittedAt,
		&i.ConnectionConfigVersion,
		&i.ConnectionFingerprint,
		&i.ConnectionDisplayName,
		&i.ConnectionDbType,
		&i.ExpiresAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
	)
	return i, err
}

const getAccessRequestView = `-- name: GetAccessRequestView :one
select
    r.id, r.organization_id, r.connection_id, r.requester_id, r.state, r.state_reason, r.payload_key_version, r.payload_wrapped_dek, r.payload_nonce, r.payload_ciphertext, r.payload_digest, r.payload_digest_key_version, r.redacted_sql, r.statement_class, r.policy_version, r.required_approvals, r.submitted_at, r.connection_config_version, r.connection_fingerprint, r.connection_display_name, r.connection_db_type, r.expires_at, r.version, r.created_at, r.updated_at, r.title,
    u.email as requester_email,
    u.display_name as requester_display_name,
    -- The name this request was SUBMITTED against wins; a draft has no snapshot yet, so it shows the connection as it is now (PRD §4.3 — renaming a connection must not rewrite what a past request was approved for).
    coalesce(r.connection_display_name, c.display_name) as connection_name,
    -- The badge, decided HERE. The same expression filters and counts below, so one evaluation of now() settles all three; recomputing it in the response from the app's clock let a row be counted approved and rendered expired (ADR-0018 §92), and any skew between the two machines widened the gap.
    (case when r.state = 'approved' and (r.expires_at is null or r.expires_at <= now()) then 'expired' else r.state end)::text
        as effective_state,
    -- coalesced because state_reason is null for requester/approver actions and the domain models "no reason" as the empty string, not as absence.
    coalesce(case when r.state = 'approved' and (r.expires_at is null or r.expires_at <= now()) then 'ttl_expired' else r.state_reason end, '')::text
        as effective_reason,
    (
        select count(*) from public.approvals a
        join public.users au on au.id = a.approver_id and au.status = 'active'
        where a.request_id = r.id and a.organization_id = r.organization_id
          and a.decision = 'approved' and a.approver_id <> r.requester_id
          and exists (
              select 1 from public.organization_memberships m
              join public.roles ro on ro.id = m.role_id and ro.deleted_at is null
              join public.role_permissions rp on rp.role_id = m.role_id
              where m.organization_id = a.organization_id and m.user_id = a.approver_id
                and rp.permission_key = 'requests.approve'
          )
    )::bigint as valid_approvals,
    -- Count within the same query before pagination so rows, effective-state filtering, and total share one snapshot.
    count(*) over ()::bigint as total_count
from public.access_requests r
join public.users u on u.id = r.requester_id
join public.connections c on c.id = r.connection_id
where r.id = $1 and r.organization_id = $2
`

type GetAccessRequestViewParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

type GetAccessRequestViewRow struct {
	ID                      pgtype.UUID
	OrganizationID          pgtype.UUID
	ConnectionID            pgtype.UUID
	RequesterID             pgtype.UUID
	State                   string
	StateReason             *string
	PayloadKeyVersion       int32
	PayloadWrappedDek       []byte
	PayloadNonce            []byte
	PayloadCiphertext       []byte
	PayloadDigest           []byte
	PayloadDigestKeyVersion *int32
	RedactedSql             *string
	StatementClass          *string
	PolicyVersion           *int64
	RequiredApprovals       *int32
	SubmittedAt             pgtype.Timestamptz
	ConnectionConfigVersion *int64
	ConnectionFingerprint   *string
	ConnectionDisplayName   *string
	ConnectionDbType        *string
	ExpiresAt               pgtype.Timestamptz
	Version                 int64
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	Title                   string
	RequesterEmail          string
	RequesterDisplayName    string
	ConnectionName          string
	EffectiveState          string
	EffectiveReason         string
	ValidApprovals          int64
	TotalCount              int64
}

// Return requester, target, and current valid-approval count together. Keep detail and list projections aligned for their shared Go row type.
func (q *Queries) GetAccessRequestView(ctx context.Context, arg GetAccessRequestViewParams) (GetAccessRequestViewRow, error) {
	row := q.db.QueryRow(ctx, getAccessRequestView, arg.ID, arg.OrganizationID)
	var i GetAccessRequestViewRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ConnectionID,
		&i.RequesterID,
		&i.State,
		&i.StateReason,
		&i.PayloadKeyVersion,
		&i.PayloadWrappedDek,
		&i.PayloadNonce,
		&i.PayloadCiphertext,
		&i.PayloadDigest,
		&i.PayloadDigestKeyVersion,
		&i.RedactedSql,
		&i.StatementClass,
		&i.PolicyVersion,
		&i.RequiredApprovals,
		&i.SubmittedAt,
		&i.ConnectionConfigVersion,
		&i.ConnectionFingerprint,
		&i.ConnectionDisplayName,
		&i.ConnectionDbType,
		&i.ExpiresAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.RequesterEmail,
		&i.RequesterDisplayName,
		&i.ConnectionName,
		&i.EffectiveState,
		&i.EffectiveReason,
		&i.ValidApprovals,
		&i.TotalCount,
	)
	return i, err
}

const insertAccessRequest = `-- name: InsertAccessRequest :exec
insert into public.access_requests (
    id, organization_id, connection_id, requester_id, title,
    payload_key_version, payload_wrapped_dek, payload_nonce, payload_ciphertext,
    created_at, updated_at
) values (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10::timestamptz, $10::timestamptz
)
`

type InsertAccessRequestParams struct {
	ID                pgtype.UUID
	OrganizationID    pgtype.UUID
	ConnectionID      pgtype.UUID
	RequesterID       pgtype.UUID
	Title             string
	PayloadKeyVersion int32
	PayloadWrappedDek []byte
	PayloadNonce      []byte
	PayloadCiphertext []byte
	At                pgtype.Timestamptz
}

// created_at/updated_at are given explicitly rather than left to the column DEFAULT: this insert runs after a FOR SHARE wait on the connection, and the default is now() — the transaction's start time, which predates the wait (ADR-0009).
func (q *Queries) InsertAccessRequest(ctx context.Context, arg InsertAccessRequestParams) error {
	_, err := q.db.Exec(ctx, insertAccessRequest,
		arg.ID,
		arg.OrganizationID,
		arg.ConnectionID,
		arg.RequesterID,
		arg.Title,
		arg.PayloadKeyVersion,
		arg.PayloadWrappedDek,
		arg.PayloadNonce,
		arg.PayloadCiphertext,
		arg.At,
	)
	return err
}

const insertApproval = `-- name: InsertApproval :one
insert into public.approvals (request_id, organization_id, approver_id, decision, reason, decided_at)
values ($1, $2, $3, $4, $5, clock_timestamp())
returning decided_at
`

type InsertApprovalParams struct {
	RequestID      pgtype.UUID
	OrganizationID pgtype.UUID
	ApproverID     pgtype.UUID
	Decision       string
	Reason         string
}

// Read clock_timestamp() after the request lock and reuse the returned instant for approval, transition, expiry, and audit.
func (q *Queries) InsertApproval(ctx context.Context, arg InsertApprovalParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, insertApproval,
		arg.RequestID,
		arg.OrganizationID,
		arg.ApproverID,
		arg.Decision,
		arg.Reason,
	)
	var decided_at pgtype.Timestamptz
	err := row.Scan(&decided_at)
	return decided_at, err
}

const listAccessRequestsAsc = `-- name: ListAccessRequestsAsc :many
select
    r.id, r.organization_id, r.connection_id, r.requester_id, r.state, r.state_reason, r.payload_key_version, r.payload_wrapped_dek, r.payload_nonce, r.payload_ciphertext, r.payload_digest, r.payload_digest_key_version, r.redacted_sql, r.statement_class, r.policy_version, r.required_approvals, r.submitted_at, r.connection_config_version, r.connection_fingerprint, r.connection_display_name, r.connection_db_type, r.expires_at, r.version, r.created_at, r.updated_at, r.title,
    u.email as requester_email,
    u.display_name as requester_display_name,
    -- The name this request was SUBMITTED against wins; a draft has no snapshot yet, so it shows the connection as it is now (PRD §4.3 — renaming a connection must not rewrite what a past request was approved for).
    coalesce(r.connection_display_name, c.display_name) as connection_name,
    -- The badge, decided HERE. The same expression filters and counts below, so one evaluation of now() settles all three; recomputing it in the response from the app's clock let a row be counted approved and rendered expired (ADR-0018 §92), and any skew between the two machines widened the gap.
    (case when r.state = 'approved' and (r.expires_at is null or r.expires_at <= now()) then 'expired' else r.state end)::text
        as effective_state,
    -- coalesced because state_reason is null for requester/approver actions and the domain models "no reason" as the empty string, not as absence.
    coalesce(case when r.state = 'approved' and (r.expires_at is null or r.expires_at <= now()) then 'ttl_expired' else r.state_reason end, '')::text
        as effective_reason,
    (
        select count(*) from public.approvals a
        join public.users au on au.id = a.approver_id and au.status = 'active'
        where a.request_id = r.id and a.organization_id = r.organization_id
          and a.decision = 'approved' and a.approver_id <> r.requester_id
          and exists (
              select 1 from public.organization_memberships m
              join public.roles ro on ro.id = m.role_id and ro.deleted_at is null
              join public.role_permissions rp on rp.role_id = m.role_id
              where m.organization_id = a.organization_id and m.user_id = a.approver_id
                and rp.permission_key = 'requests.approve'
          )
    )::bigint as valid_approvals,
    -- Count within the same query before pagination so rows, effective-state filtering, and total share one snapshot.
    count(*) over ()::bigint as total_count
from public.access_requests r
join public.users u on u.id = r.requester_id
join public.connections c on c.id = r.connection_id
where r.organization_id = $1
  and ($2::text is null
       or (case when r.state = 'approved' and (r.expires_at is null or r.expires_at <= now()) then 'expired' else r.state end) = $2)
  and ($3::uuid is null or r.requester_id = $3)
order by r.created_at asc, r.id asc
limit $5::bigint offset $4::bigint
`

type ListAccessRequestsAscParams struct {
	OrganizationID pgtype.UUID
	State          *string
	RequesterID    pgtype.UUID
	RowOffset      int64
	PageLimit      int64
}

type ListAccessRequestsAscRow struct {
	ID                      pgtype.UUID
	OrganizationID          pgtype.UUID
	ConnectionID            pgtype.UUID
	RequesterID             pgtype.UUID
	State                   string
	StateReason             *string
	PayloadKeyVersion       int32
	PayloadWrappedDek       []byte
	PayloadNonce            []byte
	PayloadCiphertext       []byte
	PayloadDigest           []byte
	PayloadDigestKeyVersion *int32
	RedactedSql             *string
	StatementClass          *string
	PolicyVersion           *int64
	RequiredApprovals       *int32
	SubmittedAt             pgtype.Timestamptz
	ConnectionConfigVersion *int64
	ConnectionFingerprint   *string
	ConnectionDisplayName   *string
	ConnectionDbType        *string
	ExpiresAt               pgtype.Timestamptz
	Version                 int64
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	Title                   string
	RequesterEmail          string
	RequesterDisplayName    string
	ConnectionName          string
	EffectiveState          string
	EffectiveReason         string
	ValidApprovals          int64
	TotalCount              int64
}

func (q *Queries) ListAccessRequestsAsc(ctx context.Context, arg ListAccessRequestsAscParams) ([]ListAccessRequestsAscRow, error) {
	rows, err := q.db.Query(ctx, listAccessRequestsAsc,
		arg.OrganizationID,
		arg.State,
		arg.RequesterID,
		arg.RowOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessRequestsAscRow{}
	for rows.Next() {
		var i ListAccessRequestsAscRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ConnectionID,
			&i.RequesterID,
			&i.State,
			&i.StateReason,
			&i.PayloadKeyVersion,
			&i.PayloadWrappedDek,
			&i.PayloadNonce,
			&i.PayloadCiphertext,
			&i.PayloadDigest,
			&i.PayloadDigestKeyVersion,
			&i.RedactedSql,
			&i.StatementClass,
			&i.PolicyVersion,
			&i.RequiredApprovals,
			&i.SubmittedAt,
			&i.ConnectionConfigVersion,
			&i.ConnectionFingerprint,
			&i.ConnectionDisplayName,
			&i.ConnectionDbType,
			&i.ExpiresAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.RequesterEmail,
			&i.RequesterDisplayName,
			&i.ConnectionName,
			&i.EffectiveState,
			&i.EffectiveReason,
			&i.ValidApprovals,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessRequestsDesc = `-- name: ListAccessRequestsDesc :many
select
    r.id, r.organization_id, r.connection_id, r.requester_id, r.state, r.state_reason, r.payload_key_version, r.payload_wrapped_dek, r.payload_nonce, r.payload_ciphertext, r.payload_digest, r.payload_digest_key_version, r.redacted_sql, r.statement_class, r.policy_version, r.required_approvals, r.submitted_at, r.connection_config_version, r.connection_fingerprint, r.connection_display_name, r.connection_db_type, r.expires_at, r.version, r.created_at, r.updated_at, r.title,
    u.email as requester_email,
    u.display_name as requester_display_name,
    -- The name this request was SUBMITTED against wins; a draft has no snapshot yet, so it shows the connection as it is now (PRD §4.3 — renaming a connection must not rewrite what a past request was approved for).
    coalesce(r.connection_display_name, c.display_name) as connection_name,
    -- The badge, decided HERE. The same expression filters and counts below, so one evaluation of now() settles all three; recomputing it in the response from the app's clock let a row be counted approved and rendered expired (ADR-0018 §92), and any skew between the two machines widened the gap.
    (case when r.state = 'approved' and (r.expires_at is null or r.expires_at <= now()) then 'expired' else r.state end)::text
        as effective_state,
    -- coalesced because state_reason is null for requester/approver actions and the domain models "no reason" as the empty string, not as absence.
    coalesce(case when r.state = 'approved' and (r.expires_at is null or r.expires_at <= now()) then 'ttl_expired' else r.state_reason end, '')::text
        as effective_reason,
    (
        select count(*) from public.approvals a
        join public.users au on au.id = a.approver_id and au.status = 'active'
        where a.request_id = r.id and a.organization_id = r.organization_id
          and a.decision = 'approved' and a.approver_id <> r.requester_id
          and exists (
              select 1 from public.organization_memberships m
              join public.roles ro on ro.id = m.role_id and ro.deleted_at is null
              join public.role_permissions rp on rp.role_id = m.role_id
              where m.organization_id = a.organization_id and m.user_id = a.approver_id
                and rp.permission_key = 'requests.approve'
          )
    )::bigint as valid_approvals,
    -- Count within the same query before pagination so rows, effective-state filtering, and total share one snapshot.
    count(*) over ()::bigint as total_count
from public.access_requests r
join public.users u on u.id = r.requester_id
join public.connections c on c.id = r.connection_id
where r.organization_id = $1
  and ($2::text is null
       or (case when r.state = 'approved' and (r.expires_at is null or r.expires_at <= now()) then 'expired' else r.state end) = $2)
  and ($3::uuid is null or r.requester_id = $3)
order by r.created_at desc, r.id desc
limit $5::bigint offset $4::bigint
`

type ListAccessRequestsDescParams struct {
	OrganizationID pgtype.UUID
	State          *string
	RequesterID    pgtype.UUID
	RowOffset      int64
	PageLimit      int64
}

type ListAccessRequestsDescRow struct {
	ID                      pgtype.UUID
	OrganizationID          pgtype.UUID
	ConnectionID            pgtype.UUID
	RequesterID             pgtype.UUID
	State                   string
	StateReason             *string
	PayloadKeyVersion       int32
	PayloadWrappedDek       []byte
	PayloadNonce            []byte
	PayloadCiphertext       []byte
	PayloadDigest           []byte
	PayloadDigestKeyVersion *int32
	RedactedSql             *string
	StatementClass          *string
	PolicyVersion           *int64
	RequiredApprovals       *int32
	SubmittedAt             pgtype.Timestamptz
	ConnectionConfigVersion *int64
	ConnectionFingerprint   *string
	ConnectionDisplayName   *string
	ConnectionDbType        *string
	ExpiresAt               pgtype.Timestamptz
	Version                 int64
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	Title                   string
	RequesterEmail          string
	RequesterDisplayName    string
	ConnectionName          string
	EffectiveState          string
	EffectiveReason         string
	ValidApprovals          int64
	TotalCount              int64
}

// Filter by effective state and requester, then paginate newest-first with an ID tie-breaker; include current valid-approval counts.
func (q *Queries) ListAccessRequestsDesc(ctx context.Context, arg ListAccessRequestsDescParams) ([]ListAccessRequestsDescRow, error) {
	rows, err := q.db.Query(ctx, listAccessRequestsDesc,
		arg.OrganizationID,
		arg.State,
		arg.RequesterID,
		arg.RowOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessRequestsDescRow{}
	for rows.Next() {
		var i ListAccessRequestsDescRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ConnectionID,
			&i.RequesterID,
			&i.State,
			&i.StateReason,
			&i.PayloadKeyVersion,
			&i.PayloadWrappedDek,
			&i.PayloadNonce,
			&i.PayloadCiphertext,
			&i.PayloadDigest,
			&i.PayloadDigestKeyVersion,
			&i.RedactedSql,
			&i.StatementClass,
			&i.PolicyVersion,
			&i.RequiredApprovals,
			&i.SubmittedAt,
			&i.ConnectionConfigVersion,
			&i.ConnectionFingerprint,
			&i.ConnectionDisplayName,
			&i.ConnectionDbType,
			&i.ExpiresAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.RequesterEmail,
			&i.RequesterDisplayName,
			&i.ConnectionName,
			&i.EffectiveState,
			&i.EffectiveReason,
			&i.ValidApprovals,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalsForRequest = `-- name: ListApprovalsForRequest :many
select
    a.id, a.request_id, a.organization_id, a.approver_id, a.decision, a.reason, a.decided_at,
    u.email as approver_email,
    u.display_name as approver_display_name,
    (
        a.decision = 'approved'
        and u.status = 'active'
        and a.approver_id <> $1
        and exists (
            select 1
            from public.organization_memberships m
            join public.roles r on r.id = m.role_id and r.deleted_at is null
            join public.role_permissions rp on rp.role_id = m.role_id
            where m.organization_id = a.organization_id
              and m.user_id = a.approver_id
              and rp.permission_key = 'requests.approve'
        )
    )::boolean as valid
from public.approvals a
join public.users u on u.id = a.approver_id
where a.request_id = $2 and a.organization_id = $3
order by a.decided_at asc, a.id asc
`

type ListApprovalsForRequestParams struct {
	RequesterID    pgtype.UUID
	RequestID      pgtype.UUID
	OrganizationID pgtype.UUID
}

type ListApprovalsForRequestRow struct {
	ID                  pgtype.UUID
	RequestID           pgtype.UUID
	OrganizationID      pgtype.UUID
	ApproverID          pgtype.UUID
	Decision            string
	Reason              string
	DecidedAt           pgtype.Timestamptz
	ApproverEmail       string
	ApproverDisplayName string
	Valid               bool
}

// Every decision with its display fields and computed validity (same predicate as CountValidApprovals). Rejections are listed but never "valid approvals".
func (q *Queries) ListApprovalsForRequest(ctx context.Context, arg ListApprovalsForRequestParams) ([]ListApprovalsForRequestRow, error) {
	rows, err := q.db.Query(ctx, listApprovalsForRequest, arg.RequesterID, arg.RequestID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovalsForRequestRow{}
	for rows.Next() {
		var i ListApprovalsForRequestRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.OrganizationID,
			&i.ApproverID,
			&i.Decision,
			&i.Reason,
			&i.DecidedAt,
			&i.ApproverEmail,
			&i.ApproverDisplayName,
			&i.Valid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestableConnections = `-- name: ListRequestableConnections :many
select id, display_name, db_type, environment
from public.connections
where organization_id = $1 and archived_at is null
order by display_name asc, id asc
`

type ListRequestableConnectionsRow struct {
	ID          pgtype.UUID
	DisplayName string
	DbType      string
	Environment string
}

// Return active target summaries under requests.create without connection-admin permissions (ADR-0008).
func (q *Queries) ListRequestableConnections(ctx context.Context, organizationID pgtype.UUID) ([]ListRequestableConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listRequestableConnections, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestableConnectionsRow{}
	for rows.Next() {
		var i ListRequestableConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.DbType,
			&i.Environment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockApproverMembership = `-- name: LockApproverMembership :many
select 1 as locked
from public.organization_memberships
where organization_id = $1 and user_id = $2
for share
`

type LockApproverMembershipParams struct {
	OrganizationID pgtype.UUID
	ApproverID     pgtype.UUID
}

// Lock membership FOR SHARE before checking eligibility. Concurrent revocation serializes only once the future role-management path takes FOR UPDATE on the same row (ADR-0018).
func (q *Queries) LockApproverMembership(ctx context.Context, arg LockApproverMembershipParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, lockApproverMembership, arg.OrganizationID, arg.ApproverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var locked int32
		if err := rows.Scan(&locked); err != nil {
			return nil, err
		}
		items = append(items, locked)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConnectionForRequest = `-- name: LockConnectionForRequest :one

select id, organization_id, archived_at, current_policy_version, config_version, target_fingerprint
from public.connections
where id = $1 and organization_id = $2
for share
`

type LockConnectionForRequestParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

type LockConnectionForRequestRow struct {
	ID                   pgtype.UUID
	OrganizationID       pgtype.UUID
	ArchivedAt           pgtype.Timestamptz
	CurrentPolicyVersion int64
	ConfigVersion        int64
	TargetFingerprint    string
}

// Guard state transitions and draft versions. Keep the active, permitted, non-requester approval predicate aligned across counts and views (ADR-0018).
// FOR SHARE allows concurrent request writers while serializing archive/policy changes and their cascades against request creation (ADR-0018).
func (q *Queries) LockConnectionForRequest(ctx context.Context, arg LockConnectionForRequestParams) (LockConnectionForRequestRow, error) {
	row := q.db.QueryRow(ctx, lockConnectionForRequest, arg.ID, arg.OrganizationID)
	var i LockConnectionForRequestRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ArchivedAt,
		&i.CurrentPolicyVersion,
		&i.ConfigVersion,
		&i.TargetFingerprint,
	)
	return i, err
}

const lockLiveRequestsForConnection = `-- name: LockLiveRequestsForConnection :many
select id from public.access_requests
where connection_id = $1 and organization_id = $2
  and state in ('pending', 'approved')
for update
`

type LockLiveRequestsForConnectionParams struct {
	ConnectionID   pgtype.UUID
	OrganizationID pgtype.UUID
}

// The config-replacement cascade's half of LockSweptRequestsForConnection: it touches pending/approved only, so it locks only those. Drafts survive a config change — the connection is still there and a draft carries no approval, so it can simply be submitted against the new configuration (unlike archive, which takes the connection away entirely).
func (q *Queries) LockLiveRequestsForConnection(ctx context.Context, arg LockLiveRequestsForConnectionParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, lockLiveRequestsForConnection, arg.ConnectionID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSweptRequestsForConnection = `-- name: LockSweptRequestsForConnection :many
select id from public.access_requests
where connection_id = $1 and organization_id = $2
  and state in ('draft', 'pending', 'approved')
for update
`

type LockSweptRequestsForConnectionParams struct {
	ConnectionID   pgtype.UUID
	OrganizationID pgtype.UUID
}

// Lock cascade request rows before observing time. The caller’s exclusive connection lock prevents new requests from appearing behind the sweep.
func (q *Queries) LockSweptRequestsForConnection(ctx context.Context, arg LockSweptRequestsForConnectionParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, lockSweptRequestsForConnection, arg.ConnectionID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const observeWallClock = `-- name: ObserveWallClock :one
select clock_timestamp()::timestamptz as at
`

// Observe time in a separate statement after all locks; an inline UPDATE timestamp may be evaluated before its lock wait.
func (q *Queries) ObserveWallClock(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, observeWallClock)
	var at pgtype.Timestamptz
	err := row.Scan(&at)
	return at, err
}

const submitAccessRequest = `-- name: SubmitAccessRequest :one
with stamped as materialized (select clock_timestamp() as at)
update public.access_requests
set state = $1,
    statement_class = $2,
    policy_version = $3,
    connection_config_version = $4,
    connection_fingerprint = $5,
    connection_display_name = $6,
    connection_db_type = $7,
    required_approvals = $8,
    payload_digest = $9,
    payload_digest_key_version = $10,
    redacted_sql = $11,
    -- The submission's own moment, from the same CTE as everything else here. It used to be the caller's clock, computed before this transaction existed: with any app-server skew a request could be filed as submitted AFTER the auto-approval it triggered, in the same statement that stamps updated_at from the database (ADR-0009's event-time rule).
    submitted_at = (select at from stamped),
    expires_at = case when $1::text = 'approved'
                     then (select at from stamped) + make_interval(secs => $12::float8)
                     else null end,
    version = version + 1,
    updated_at = (select at from stamped)
where id = $13 and organization_id = $14
  and state = 'draft' and version = $15
returning id, organization_id, connection_id, requester_id, state, state_reason, payload_key_version, payload_wrapped_dek, payload_nonce, payload_ciphertext, payload_digest, payload_digest_key_version, redacted_sql, statement_class, policy_version, required_approvals, submitted_at, connection_config_version, connection_fingerprint, connection_display_name, connection_db_type, expires_at, version, created_at, updated_at, title
`

type SubmitAccessRequestParams struct {
	State                   string
	StatementClass          *string
	PolicyVersion           *int64
	ConnectionConfigVersion *int64
	ConnectionFingerprint   *string
	ConnectionDisplayName   *string
	ConnectionDbType        *string
	RequiredApprovals       *int32
	PayloadDigest           []byte
	PayloadDigestKeyVersion *int32
	RedactedSql             *string
	ValiditySeconds         float64
	ID                      pgtype.UUID
	OrganizationID          pgtype.UUID
	ExpectedVersion         int64
}

// Stamp submission, updated_at, and quorum-zero approval expiry from one post-lock database instant; reuse it in derived audit evidence.
func (q *Queries) SubmitAccessRequest(ctx context.Context, arg SubmitAccessRequestParams) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, submitAccessRequest,
		arg.State,
		arg.StatementClass,
		arg.PolicyVersion,
		arg.ConnectionConfigVersion,
		arg.ConnectionFingerprint,
		arg.ConnectionDisplayName,
		arg.ConnectionDbType,
		arg.RequiredApprovals,
		arg.PayloadDigest,
		arg.PayloadDigestKeyVersion,
		arg.RedactedSql,
		arg.ValiditySeconds,
		arg.ID,
		arg.OrganizationID,
		arg.ExpectedVersion,
	)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ConnectionID,
		&i.RequesterID,
		&i.State,
		&i.StateReason,
		&i.PayloadKeyVersion,
		&i.PayloadWrappedDek,
		&i.PayloadNonce,
		&i.PayloadCiphertext,
		&i.PayloadDigest,
		&i.PayloadDigestKeyVersion,
		&i.RedactedSql,
		&i.StatementClass,
		&i.PolicyVersion,
		&i.RequiredApprovals,
		&i.SubmittedAt,
		&i.ConnectionConfigVersion,
		&i.ConnectionFingerprint,
		&i.ConnectionDisplayName,
		&i.ConnectionDbType,
		&i.ExpiresAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
	)
	return i, err
}

const transitionAccessRequest = `-- name: TransitionAccessRequest :one
update public.access_requests
set state = $1,
    state_reason = $2,
    expires_at = coalesce($3, expires_at),
    version = version + 1,
    updated_at = coalesce($4::timestamptz, clock_timestamp())
where id = $5 and organization_id = $6 and state = $7
returning id, organization_id, connection_id, requester_id, state, state_reason, payload_key_version, payload_wrapped_dek, payload_nonce, payload_ciphertext, payload_digest, payload_digest_key_version, redacted_sql, statement_class, policy_version, required_approvals, submitted_at, connection_config_version, connection_fingerprint, connection_display_name, connection_db_type, expires_at, version, created_at, updated_at, title
`

type TransitionAccessRequestParams struct {
	NextState      string
	StateReason    *string
	ExpiresAt      pgtype.Timestamptz
	DecidedAt      pgtype.Timestamptz
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	FromState      string
}

// Use the decision’s observed instant for transition and approval expiry; otherwise clock_timestamp() avoids dating writes before lock waits.
func (q *Queries) TransitionAccessRequest(ctx context.Context, arg TransitionAccessRequestParams) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, transitionAccessRequest,
		arg.NextState,
		arg.StateReason,
		arg.ExpiresAt,
		arg.DecidedAt,
		arg.ID,
		arg.OrganizationID,
		arg.FromState,
	)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ConnectionID,
		&i.RequesterID,
		&i.State,
		&i.StateReason,
		&i.PayloadKeyVersion,
		&i.PayloadWrappedDek,
		&i.PayloadNonce,
		&i.PayloadCiphertext,
		&i.PayloadDigest,
		&i.PayloadDigestKeyVersion,
		&i.RedactedSql,
		&i.StatementClass,
		&i.PolicyVersion,
		&i.RequiredApprovals,
		&i.SubmittedAt,
		&i.ConnectionConfigVersion,
		&i.ConnectionFingerprint,
		&i.ConnectionDisplayName,
		&i.ConnectionDbType,
		&i.ExpiresAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
	)
	return i, err
}

const updateAccessRequestDraftPayload = `-- name: UpdateAccessRequestDraftPayload :one
update public.access_requests
set title = $1,
    payload_key_version = $2,
    payload_wrapped_dek = $3,
    payload_nonce = $4,
    payload_ciphertext = $5,
    version = version + 1,
    -- The caller's observed instant, taken after it locked this row: now() is the transaction's start time and the lock may have held it for a while (ADR-0009).
    updated_at = $6::timestamptz
where id = $7 and organization_id = $8
  and state = 'draft' and version = $9
returning id, organization_id, connection_id, requester_id, state, state_reason, payload_key_version, payload_wrapped_dek, payload_nonce, payload_ciphertext, payload_digest, payload_digest_key_version, redacted_sql, statement_class, policy_version, required_approvals, submitted_at, connection_config_version, connection_fingerprint, connection_display_name, connection_db_type, expires_at, version, created_at, updated_at, title
`

type UpdateAccessRequestDraftPayloadParams struct {
	Title             string
	PayloadKeyVersion int32
	PayloadWrappedDek []byte
	PayloadNonce      []byte
	PayloadCiphertext []byte
	At                pgtype.Timestamptz
	ID                pgtype.UUID
	OrganizationID    pgtype.UUID
	ExpectedVersion   int64
}

func (q *Queries) UpdateAccessRequestDraftPayload(ctx context.Context, arg UpdateAccessRequestDraftPayloadParams) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, updateAccessRequestDraftPayload,
		arg.Title,
		arg.PayloadKeyVersion,
		arg.PayloadWrappedDek,
		arg.PayloadNonce,
		arg.PayloadCiphertext,
		arg.At,
		arg.ID,
		arg.OrganizationID,
		arg.ExpectedVersion,
	)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ConnectionID,
		&i.RequesterID,
		&i.State,
		&i.StateReason,
		&i.PayloadKeyVersion,
		&i.PayloadWrappedDek,
		&i.PayloadNonce,
		&i.PayloadCiphertext,
		&i.PayloadDigest,
		&i.PayloadDigestKeyVersion,
		&i.RedactedSql,
		&i.StatementClass,
		&i.PolicyVersion,
		&i.RequiredApprovals,
		&i.SubmittedAt,
		&i.ConnectionConfigVersion,
		&i.ConnectionFingerprint,
		&i.ConnectionDisplayName,
		&i.ConnectionDbType,
		&i.ExpiresAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
	)
	return i, err
}
