// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: administration.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAdministrators = `-- name: CountActiveAdministrators :one
select count(*)
from public.organization_memberships m
join public.users u on u.id = m.user_id and u.status = 'active'
join public.roles r on r.id = m.role_id and r.organization_id = m.organization_id and r.deleted_at is null
where m.organization_id = $1
  and (select count(distinct rp.permission_key)
       from public.role_permissions rp
       where rp.role_id = m.role_id and rp.deleted_at is null and rp.permission_key = any($2::text[]))
      = cardinality($2::text[])
`

type CountActiveAdministratorsParams struct {
	OrganizationID           pgtype.UUID
	AdministratorPermissions []string
}

// Active members whose live role holds every administrator permission key (ADR-0008); the keys come from the domain rule.
func (q *Queries) CountActiveAdministrators(ctx context.Context, arg CountActiveAdministratorsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdministrators, arg.OrganizationID, arg.AdministratorPermissions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActorAuthority = `-- name: GetActorAuthority :one
select u.status,
       coalesce(array(
           select distinct rp.permission_key
           from public.organization_memberships m
           join public.roles r on r.id = m.role_id and r.deleted_at is null
           join public.role_permissions rp on rp.role_id = m.role_id and rp.deleted_at is null
           where m.organization_id = $1 and m.user_id = u.id
           order by rp.permission_key
       ), '{}')::text[] as permissions
from public.users u
where u.id = $2
`

type GetActorAuthorityParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
}

type GetActorAuthorityRow struct {
	Status      string
	Permissions []string
}

// Actor status and live permissions, read under the administration lock (ADR-0053).
func (q *Queries) GetActorAuthority(ctx context.Context, arg GetActorAuthorityParams) (GetActorAuthorityRow, error) {
	row := q.db.QueryRow(ctx, getActorAuthority, arg.OrganizationID, arg.UserID)
	var i GetActorAuthorityRow
	err := row.Scan(&i.Status, &i.Permissions)
	return i, err
}

const getMember = `-- name: GetMember :one
select u.id, u.email, u.display_name, u.status, u.created_at, m.role_id, r.name as role_name,
       exists (select 1 from public.auth_methods am where am.user_id = u.id and am.type = 'password')::boolean as has_password
from public.organization_memberships m
join public.users u on u.id = m.user_id
join public.roles r on r.id = m.role_id and r.organization_id = m.organization_id
where m.organization_id = $1 and m.user_id = $2
`

type GetMemberParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
}

type GetMemberRow struct {
	ID          pgtype.UUID
	Email       string
	DisplayName string
	Status      string
	CreatedAt   pgtype.Timestamptz
	RoleID      pgtype.UUID
	RoleName    string
	HasPassword bool
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (GetMemberRow, error) {
	row := q.db.QueryRow(ctx, getMember, arg.OrganizationID, arg.UserID)
	var i GetMemberRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.RoleID,
		&i.RoleName,
		&i.HasPassword,
	)
	return i, err
}

const getRoleState = `-- name: GetRoleState :one
select r.is_system, r.version, (r.deleted_at is not null)::boolean as deleted,
       exists (select 1 from public.organization_memberships m where m.role_id = r.id and m.organization_id = r.organization_id)::boolean as assigned
from public.roles r
where r.organization_id = $1 and r.id = $2
`

type GetRoleStateParams struct {
	OrganizationID pgtype.UUID
	RoleID         pgtype.UUID
}

type GetRoleStateRow struct {
	IsSystem bool
	Version  int64
	Deleted  bool
	Assigned bool
}

// Disambiguates a refused role update or delete, including soft-deleted rows.
func (q *Queries) GetRoleState(ctx context.Context, arg GetRoleStateParams) (GetRoleStateRow, error) {
	row := q.db.QueryRow(ctx, getRoleState, arg.OrganizationID, arg.RoleID)
	var i GetRoleStateRow
	err := row.Scan(
		&i.IsSystem,
		&i.Version,
		&i.Deleted,
		&i.Assigned,
	)
	return i, err
}

const getRoleWithPermissions = `-- name: GetRoleWithPermissions :one
select r.id, r.name, r.is_system, r.version,
       coalesce(array_agg(rp.permission_key order by rp.permission_key) filter (where rp.permission_key is not null), '{}')::text[] as permissions,
       (select count(*) from public.organization_memberships m where m.role_id = r.id and m.organization_id = r.organization_id) as member_count
from public.roles r
left join public.role_permissions rp on rp.role_id = r.id and rp.deleted_at is null
where r.organization_id = $1 and r.id = $2 and r.deleted_at is null
group by r.id
`

type GetRoleWithPermissionsParams struct {
	OrganizationID pgtype.UUID
	RoleID         pgtype.UUID
}

type GetRoleWithPermissionsRow struct {
	ID          pgtype.UUID
	Name        string
	IsSystem    bool
	Version     int64
	Permissions []string
	MemberCount int64
}

func (q *Queries) GetRoleWithPermissions(ctx context.Context, arg GetRoleWithPermissionsParams) (GetRoleWithPermissionsRow, error) {
	row := q.db.QueryRow(ctx, getRoleWithPermissions, arg.OrganizationID, arg.RoleID)
	var i GetRoleWithPermissionsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsSystem,
		&i.Version,
		&i.Permissions,
		&i.MemberCount,
	)
	return i, err
}

const grantRolePermissions = `-- name: GrantRolePermissions :exec
insert into public.role_permissions (role_id, permission_key)
select $1, unnest($2::text[])
on conflict (role_id, permission_key) do update set deleted_at = null
where role_permissions.deleted_at is not null
`

type GrantRolePermissionsParams struct {
	RoleID         pgtype.UUID
	PermissionKeys []string
}

// Insert the role's permissions, reviving any soft-deleted row of the same key instead of adding a second one (ADR-0053).
func (q *Queries) GrantRolePermissions(ctx context.Context, arg GrantRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, grantRolePermissions, arg.RoleID, arg.PermissionKeys)
	return err
}

const insertPasswordSetupToken = `-- name: InsertPasswordSetupToken :one
insert into public.password_setup_tokens (organization_id, user_id, token_hash, expires_at, created_at)
select $1, $2, $3, stamped.at + stamped.validity, stamped.at
from (select $4::timestamptz as at, make_interval(secs => $5::float8) as validity) as stamped
returning expires_at
`

type InsertPasswordSetupTokenParams struct {
	OrganizationID  pgtype.UUID
	UserID          pgtype.UUID
	TokenHash       []byte
	At              pgtype.Timestamptz
	ValiditySeconds float64
}

// The expiry is measured from the observed instant on the database clock.
func (q *Queries) InsertPasswordSetupToken(ctx context.Context, arg InsertPasswordSetupTokenParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, insertPasswordSetupToken,
		arg.OrganizationID,
		arg.UserID,
		arg.TokenHash,
		arg.At,
		arg.ValiditySeconds,
	)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const insertRole = `-- name: InsertRole :one
insert into public.roles (organization_id, name, is_system, is_bootstrap_default, version, created_at)
values ($1, $2, false, false, 1, $3::timestamptz)
returning id
`

type InsertRoleParams struct {
	OrganizationID pgtype.UUID
	Name           string
	At             pgtype.Timestamptz
}

func (q *Queries) InsertRole(ctx context.Context, arg InsertRoleParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertRole, arg.OrganizationID, arg.Name, arg.At)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listMembers = `-- name: ListMembers :many
select u.id, u.email, u.display_name, u.status, u.created_at, m.role_id, r.name as role_name,
       exists (select 1 from public.auth_methods am where am.user_id = u.id and am.type = 'password')::boolean as has_password
from public.organization_memberships m
join public.users u on u.id = m.user_id
join public.roles r on r.id = m.role_id and r.organization_id = m.organization_id
where m.organization_id = $1
order by lower(u.email), u.id
`

type ListMembersRow struct {
	ID          pgtype.UUID
	Email       string
	DisplayName string
	Status      string
	CreatedAt   pgtype.Timestamptz
	RoleID      pgtype.UUID
	RoleName    string
	HasPassword bool
}

// Users seen through their membership in one organization (ADR-0004/0053), with the single assigned role and whether a password credential exists.
func (q *Queries) ListMembers(ctx context.Context, organizationID pgtype.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Status,
			&i.CreatedAt,
			&i.RoleID,
			&i.RoleName,
			&i.HasPassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesWithPermissions = `-- name: ListRolesWithPermissions :many
select r.id, r.name, r.is_system, r.version,
       coalesce(array_agg(rp.permission_key order by rp.permission_key) filter (where rp.permission_key is not null), '{}')::text[] as permissions,
       (select count(*) from public.organization_memberships m where m.role_id = r.id and m.organization_id = r.organization_id) as member_count
from public.roles r
left join public.role_permissions rp on rp.role_id = r.id and rp.deleted_at is null
where r.organization_id = $1 and r.deleted_at is null
group by r.id
order by r.is_system desc, lower(r.name), r.id
`

type ListRolesWithPermissionsRow struct {
	ID          pgtype.UUID
	Name        string
	IsSystem    bool
	Version     int64
	Permissions []string
	MemberCount int64
}

func (q *Queries) ListRolesWithPermissions(ctx context.Context, organizationID pgtype.UUID) ([]ListRolesWithPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listRolesWithPermissions, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesWithPermissionsRow{}
	for rows.Next() {
		var i ListRolesWithPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsSystem,
			&i.Version,
			&i.Permissions,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMember = `-- name: LockMember :one
select u.status,
       exists (select 1 from public.auth_methods am where am.user_id = u.id and am.type = 'password')::boolean as has_password
from public.organization_memberships m
join public.users u on u.id = m.user_id
where m.organization_id = $1 and m.user_id = $2
for update of u, m
`

type LockMemberParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
}

type LockMemberRow struct {
	Status      string
	HasPassword bool
}

// Lock the account and its membership for a status, role or setup-link change; a user without a membership in the organization is not found.
func (q *Queries) LockMember(ctx context.Context, arg LockMemberParams) (LockMemberRow, error) {
	row := q.db.QueryRow(ctx, lockMember, arg.OrganizationID, arg.UserID)
	var i LockMemberRow
	err := row.Scan(&i.Status, &i.HasPassword)
	return i, err
}

const revokeOpenPasswordSetups = `-- name: RevokeOpenPasswordSetups :exec
update public.password_setup_tokens set revoked_at = $1::timestamptz
where user_id = $2 and consumed_at is null and revoked_at is null
`

type RevokeOpenPasswordSetupsParams struct {
	At     pgtype.Timestamptz
	UserID pgtype.UUID
}

func (q *Queries) RevokeOpenPasswordSetups(ctx context.Context, arg RevokeOpenPasswordSetupsParams) error {
	_, err := q.db.Exec(ctx, revokeOpenPasswordSetups, arg.At, arg.UserID)
	return err
}

const revokeRoleMemberSessionsAt = `-- name: RevokeRoleMemberSessionsAt :execrows
update public.sessions set revoked_at = $1::timestamptz
where revoked_at is null
  and user_id in (
      select m.user_id from public.organization_memberships m
      where m.organization_id = $2 and m.role_id = $3
  )
`

type RevokeRoleMemberSessionsAtParams struct {
	At             pgtype.Timestamptz
	OrganizationID pgtype.UUID
	RoleID         pgtype.UUID
}

// Revoke every active session of the organization's members holding a role whose permissions changed.
func (q *Queries) RevokeRoleMemberSessionsAt(ctx context.Context, arg RevokeRoleMemberSessionsAtParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRoleMemberSessionsAt, arg.At, arg.OrganizationID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSessionsAt = `-- name: RevokeUserSessionsAt :execrows
update public.sessions set revoked_at = $1::timestamptz
where user_id = $2 and revoked_at is null
`

type RevokeUserSessionsAtParams struct {
	At     pgtype.Timestamptz
	UserID pgtype.UUID
}

// Revoke every active session of a user at the observed instant of a privilege change (ADR-0006/0053).
func (q *Queries) RevokeUserSessionsAt(ctx context.Context, arg RevokeUserSessionsAtParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSessionsAt, arg.At, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMembershipRole = `-- name: SetMembershipRole :exec
update public.organization_memberships set role_id = $1
where organization_id = $2 and user_id = $3
`

type SetMembershipRoleParams struct {
	RoleID         pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) SetMembershipRole(ctx context.Context, arg SetMembershipRoleParams) error {
	_, err := q.db.Exec(ctx, setMembershipRole, arg.RoleID, arg.OrganizationID, arg.UserID)
	return err
}

const setUserStatus = `-- name: SetUserStatus :exec
update public.users set status = $1 where id = $2
`

type SetUserStatusParams struct {
	Status string
	UserID pgtype.UUID
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) error {
	_, err := q.db.Exec(ctx, setUserStatus, arg.Status, arg.UserID)
	return err
}

const softDeleteCustomRole = `-- name: SoftDeleteCustomRole :execrows
update public.roles set deleted_at = $1::timestamptz, version = roles.version + 1
where roles.organization_id = $2 and roles.id = $3 and roles.deleted_at is null
  and not roles.is_system and roles.version = $4
  and not exists (select 1 from public.organization_memberships m where m.role_id = roles.id and m.organization_id = roles.organization_id)
`

type SoftDeleteCustomRoleParams struct {
	At              pgtype.Timestamptz
	OrganizationID  pgtype.UUID
	RoleID          pgtype.UUID
	ExpectedVersion int64
}

func (q *Queries) SoftDeleteCustomRole(ctx context.Context, arg SoftDeleteCustomRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteCustomRole,
		arg.At,
		arg.OrganizationID,
		arg.RoleID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteRemovedRolePermissions = `-- name: SoftDeleteRemovedRolePermissions :exec
update public.role_permissions set deleted_at = $1::timestamptz
where role_id = $2 and deleted_at is null
  and permission_key <> all($3::text[])
`

type SoftDeleteRemovedRolePermissionsParams struct {
	At             pgtype.Timestamptz
	RoleID         pgtype.UUID
	PermissionKeys []string
}

// Soft-delete the role's live permissions missing from the new set; rows are never erased (ADR-0053).
func (q *Queries) SoftDeleteRemovedRolePermissions(ctx context.Context, arg SoftDeleteRemovedRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, softDeleteRemovedRolePermissions, arg.At, arg.RoleID, arg.PermissionKeys)
	return err
}

const updateCustomRole = `-- name: UpdateCustomRole :execrows
update public.roles set name = $1, version = version + 1
where organization_id = $2 and id = $3 and deleted_at is null
  and not is_system and version = $4
`

type UpdateCustomRoleParams struct {
	Name            string
	OrganizationID  pgtype.UUID
	RoleID          pgtype.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdateCustomRole(ctx context.Context, arg UpdateCustomRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCustomRole,
		arg.Name,
		arg.OrganizationID,
		arg.RoleID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
