// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
insert into public.audit_events (
    organization_id, actor_type, actor_user_id, actor_service,
    action, target_type, target_id, outcome, request_id, metadata
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertAuditEventParams struct {
	OrganizationID pgtype.UUID
	ActorType      string
	ActorUserID    pgtype.UUID
	ActorService   *string
	Action         string
	TargetType     string
	TargetID       *string
	Outcome        string
	RequestID      *string
	Metadata       []byte
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.OrganizationID,
		arg.ActorType,
		arg.ActorUserID,
		arg.ActorService,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Outcome,
		arg.RequestID,
		arg.Metadata,
	)
	return err
}
