// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertAuditEvents = `-- name: InsertAuditEvents :batchexec
insert into public.audit_events (
    organization_id, occurred_at, actor_type, actor_user_id, actor_service,
    action, target_type, target_id, outcome, request_id,
    previous_state, next_state, connection_id, query_type,
    payload_digest, payload_digest_key_version, metadata, rows_affected, duration_ms
) values ($1, coalesce($19::timestamptz, now()), $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
`

type InsertAuditEventsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertAuditEventsParams struct {
	OrganizationID          pgtype.UUID
	ActorType               string
	ActorUserID             pgtype.UUID
	ActorService            *string
	Action                  string
	TargetType              string
	TargetID                *string
	Outcome                 string
	RequestID               *string
	PreviousState           *string
	NextState               *string
	ConnectionID            pgtype.UUID
	QueryType               *string
	PayloadDigest           []byte
	PayloadDigestKeyVersion *int32
	Metadata                []byte
	RowsAffected            *int64
	DurationMs              *int64
	OccurredAt              pgtype.Timestamptz
}

// The same insert sent as one pipelined batch, so a cascade appends its derived events in one round trip while holding row locks (ADR-0009).
func (q *Queries) InsertAuditEvents(ctx context.Context, arg []InsertAuditEventsParams) *InsertAuditEventsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.OrganizationID,
			a.ActorType,
			a.ActorUserID,
			a.ActorService,
			a.Action,
			a.TargetType,
			a.TargetID,
			a.Outcome,
			a.RequestID,
			a.PreviousState,
			a.NextState,
			a.ConnectionID,
			a.QueryType,
			a.PayloadDigest,
			a.PayloadDigestKeyVersion,
			a.Metadata,
			a.RowsAffected,
			a.DurationMs,
			a.OccurredAt,
		}
		batch.Queue(insertAuditEvents, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertAuditEventsBatchResults{br, len(arg), false}
}

func (b *InsertAuditEventsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertAuditEventsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
