// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveConnection = `-- name: ArchiveConnection :one
update public.connections
set archived_at = $1::timestamptz, updated_at = $1::timestamptz, version = version + 1,
    credential_key_version = null, credential_wrapped_dek = null,
    credential_nonce = null, credential_ciphertext = null
where id = $2 and organization_id = $3 and archived_at is null
returning id, organization_id, db_type, display_name, host, port, database_name, tls_mode, target_fingerprint, credential_key_version, credential_wrapped_dek, credential_nonce, credential_ciphertext, created_by, created_at, updated_at, archived_at, version, environment, description, current_policy_version, config_version
`

type ArchiveConnectionParams struct {
	At             pgtype.Timestamptz
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

// Archive and credential discard are ONE statement (PRD §4.3 "한 작업으로 처리"). The executions slice adds the in-flight-execution guard predicate here (ADR-0014). The stamp is the caller's observed instant — the same one its request cascade uses — never now(), which is this transaction's start time and may predate the lock wait entirely (ADR-0009).
func (q *Queries) ArchiveConnection(ctx context.Context, arg ArchiveConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, archiveConnection, arg.At, arg.ID, arg.OrganizationID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DbType,
		&i.DisplayName,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.TlsMode,
		&i.TargetFingerprint,
		&i.CredentialKeyVersion,
		&i.CredentialWrappedDek,
		&i.CredentialNonce,
		&i.CredentialCiphertext,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Version,
		&i.Environment,
		&i.Description,
		&i.CurrentPolicyVersion,
		&i.ConfigVersion,
	)
	return i, err
}

const getConnection = `-- name: GetConnection :one
select id, organization_id, db_type, display_name, host, port, database_name, tls_mode, target_fingerprint, credential_key_version, credential_wrapped_dek, credential_nonce, credential_ciphertext, created_by, created_at, updated_at, archived_at, version, environment, description, current_policy_version, config_version from public.connections
where id = $1 and organization_id = $2
`

type GetConnectionParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) GetConnection(ctx context.Context, arg GetConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnection, arg.ID, arg.OrganizationID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DbType,
		&i.DisplayName,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.TlsMode,
		&i.TargetFingerprint,
		&i.CredentialKeyVersion,
		&i.CredentialWrappedDek,
		&i.CredentialNonce,
		&i.CredentialCiphertext,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Version,
		&i.Environment,
		&i.Description,
		&i.CurrentPolicyVersion,
		&i.ConfigVersion,
	)
	return i, err
}

const insertConnection = `-- name: InsertConnection :exec
insert into public.connections (
    id, organization_id, db_type, display_name, environment, description,
    host, port, database_name,
    tls_mode, target_fingerprint,
    credential_key_version, credential_wrapped_dek, credential_nonce, credential_ciphertext,
    created_by, created_at, updated_at, current_policy_version
) values (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11,
    $12, $13, $14, $15,
    $16, $17::timestamptz, $17::timestamptz, 1
)
`

type InsertConnectionParams struct {
	ID                   pgtype.UUID
	OrganizationID       pgtype.UUID
	DbType               string
	DisplayName          string
	Environment          string
	Description          string
	Host                 string
	Port                 int32
	DatabaseName         string
	TlsMode              string
	TargetFingerprint    string
	CredentialKeyVersion *int32
	CredentialWrappedDek []byte
	CredentialNonce      []byte
	CredentialCiphertext []byte
	CreatedBy            pgtype.UUID
	At                   pgtype.Timestamptz
}

// Create policy v1 in the same transaction to satisfy the deferred FK. Use post-lock database time for row and audit ordering (ADR-0009).
func (q *Queries) InsertConnection(ctx context.Context, arg InsertConnectionParams) error {
	_, err := q.db.Exec(ctx, insertConnection,
		arg.ID,
		arg.OrganizationID,
		arg.DbType,
		arg.DisplayName,
		arg.Environment,
		arg.Description,
		arg.Host,
		arg.Port,
		arg.DatabaseName,
		arg.TlsMode,
		arg.TargetFingerprint,
		arg.CredentialKeyVersion,
		arg.CredentialWrappedDek,
		arg.CredentialNonce,
		arg.CredentialCiphertext,
		arg.CreatedBy,
		arg.At,
	)
	return err
}

const listConnections = `-- name: ListConnections :many
select id, organization_id, db_type, display_name, host, port, database_name, tls_mode, target_fingerprint, credential_key_version, credential_wrapped_dek, credential_nonce, credential_ciphertext, created_by, created_at, updated_at, archived_at, version, environment, description, current_policy_version, config_version from public.connections
where organization_id = $1
  and ($2::boolean or archived_at is null)
order by created_at desc, id desc
`

type ListConnectionsParams struct {
	OrganizationID  pgtype.UUID
	IncludeArchived bool
}

func (q *Queries) ListConnections(ctx context.Context, arg ListConnectionsParams) ([]Connection, error) {
	rows, err := q.db.Query(ctx, listConnections, arg.OrganizationID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DbType,
			&i.DisplayName,
			&i.Host,
			&i.Port,
			&i.DatabaseName,
			&i.TlsMode,
			&i.TargetFingerprint,
			&i.CredentialKeyVersion,
			&i.CredentialWrappedDek,
			&i.CredentialNonce,
			&i.CredentialCiphertext,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.Version,
			&i.Environment,
			&i.Description,
			&i.CurrentPolicyVersion,
			&i.ConfigVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConnectionForWrite = `-- name: LockConnectionForWrite :one
select id from public.connections
where id = $1 and organization_id = $2
for update
`

type LockConnectionForWriteParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

// Lock before observing time so mutation timestamps follow lock waits. Updates retain their own archive predicates for precise refusal reasons.
func (q *Queries) LockConnectionForWrite(ctx context.Context, arg LockConnectionForWriteParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockConnectionForWrite, arg.ID, arg.OrganizationID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const replaceConnectionConfig = `-- name: ReplaceConnectionConfig :one
update public.connections
set display_name = $1, environment = $2, description = $3,
    host = $4, port = $5, database_name = $6, tls_mode = $7,
    target_fingerprint = $8,
    credential_key_version = $9, credential_wrapped_dek = $10,
    credential_nonce = $11, credential_ciphertext = $12,
    updated_at = $13::timestamptz, version = version + 1,
    -- The TARGET changed, so the target token moves too — this is the only statement that touches it. Requests approved against the old configuration pin the old value and are expired in this same transaction (ADR-0018); a rename must not do that, which is why this is not ` + "`" + `version` + "`" + `.
    config_version = config_version + 1
where id = $14 and organization_id = $15 and archived_at is null
  and version = $16
returning id, organization_id, db_type, display_name, host, port, database_name, tls_mode, target_fingerprint, credential_key_version, credential_wrapped_dek, credential_nonce, credential_ciphertext, created_by, created_at, updated_at, archived_at, version, environment, description, current_policy_version, config_version
`

type ReplaceConnectionConfigParams struct {
	DisplayName          string
	Environment          string
	Description          string
	Host                 string
	Port                 int32
	DatabaseName         string
	TlsMode              string
	TargetFingerprint    string
	CredentialKeyVersion *int32
	CredentialWrappedDek []byte
	CredentialNonce      []byte
	CredentialCiphertext []byte
	At                   pgtype.Timestamptz
	ID                   pgtype.UUID
	OrganizationID       pgtype.UUID
	ExpectedVersion      int64
}

// Full config replacement (ADR-0014: no partial credential edit). Archived rows are excluded — restore is a separate future flow; the store disambiguates "missing" from "archived" on a zero rowcount.
func (q *Queries) ReplaceConnectionConfig(ctx context.Context, arg ReplaceConnectionConfigParams) (Connection, error) {
	row := q.db.QueryRow(ctx, replaceConnectionConfig,
		arg.DisplayName,
		arg.Environment,
		arg.Description,
		arg.Host,
		arg.Port,
		arg.DatabaseName,
		arg.TlsMode,
		arg.TargetFingerprint,
		arg.CredentialKeyVersion,
		arg.CredentialWrappedDek,
		arg.CredentialNonce,
		arg.CredentialCiphertext,
		arg.At,
		arg.ID,
		arg.OrganizationID,
		arg.ExpectedVersion,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DbType,
		&i.DisplayName,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.TlsMode,
		&i.TargetFingerprint,
		&i.CredentialKeyVersion,
		&i.CredentialWrappedDek,
		&i.CredentialNonce,
		&i.CredentialCiphertext,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Version,
		&i.Environment,
		&i.Description,
		&i.CurrentPolicyVersion,
		&i.ConfigVersion,
	)
	return i, err
}

const updateConnectionDescriptor = `-- name: UpdateConnectionDescriptor :one
update public.connections
set display_name = $1, environment = $2, description = $3,
    updated_at = $4::timestamptz, version = version + 1
where id = $5 and organization_id = $6
  and version = $7
returning id, organization_id, db_type, display_name, host, port, database_name, tls_mode, target_fingerprint, credential_key_version, credential_wrapped_dek, credential_nonce, credential_ciphertext, created_by, created_at, updated_at, archived_at, version, environment, description, current_policy_version, config_version
`

type UpdateConnectionDescriptorParams struct {
	DisplayName     string
	Environment     string
	Description     string
	At              pgtype.Timestamptz
	ID              pgtype.UUID
	OrganizationID  pgtype.UUID
	ExpectedVersion int64
}

// Replace descriptor fields at the editor’s version, including archived history labels. Stamp with the post-lock observed instant; zero rows mean missing or stale.
func (q *Queries) UpdateConnectionDescriptor(ctx context.Context, arg UpdateConnectionDescriptorParams) (Connection, error) {
	row := q.db.QueryRow(ctx, updateConnectionDescriptor,
		arg.DisplayName,
		arg.Environment,
		arg.Description,
		arg.At,
		arg.ID,
		arg.OrganizationID,
		arg.ExpectedVersion,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DbType,
		&i.DisplayName,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.TlsMode,
		&i.TargetFingerprint,
		&i.CredentialKeyVersion,
		&i.CredentialWrappedDek,
		&i.CredentialNonce,
		&i.CredentialCiphertext,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Version,
		&i.Environment,
		&i.Description,
		&i.CurrentPolicyVersion,
		&i.ConfigVersion,
	)
	return i, err
}
