// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveConnection = `-- name: ArchiveConnection :one
update public.connections
set archived_at = now(), updated_at = now(), version = version + 1,
    credential_key_version = null, credential_wrapped_dek = null,
    credential_nonce = null, credential_ciphertext = null
where id = $1 and organization_id = $2 and archived_at is null
returning id, organization_id, db_type, display_name, host, port, database_name, tls_mode, target_fingerprint, credential_key_version, credential_wrapped_dek, credential_nonce, credential_ciphertext, created_by, created_at, updated_at, archived_at, version
`

type ArchiveConnectionParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

// Archive and credential discard are ONE statement (PRD §4.3 "한 작업으로 처리").
// The executions slice adds the in-flight-execution guard predicate here
// (ADR-0014).
func (q *Queries) ArchiveConnection(ctx context.Context, arg ArchiveConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, archiveConnection, arg.ID, arg.OrganizationID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DbType,
		&i.DisplayName,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.TlsMode,
		&i.TargetFingerprint,
		&i.CredentialKeyVersion,
		&i.CredentialWrappedDek,
		&i.CredentialNonce,
		&i.CredentialCiphertext,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Version,
	)
	return i, err
}

const getConnection = `-- name: GetConnection :one
select id, organization_id, db_type, display_name, host, port, database_name, tls_mode, target_fingerprint, credential_key_version, credential_wrapped_dek, credential_nonce, credential_ciphertext, created_by, created_at, updated_at, archived_at, version from public.connections
where id = $1 and organization_id = $2
`

type GetConnectionParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) GetConnection(ctx context.Context, arg GetConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnection, arg.ID, arg.OrganizationID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DbType,
		&i.DisplayName,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.TlsMode,
		&i.TargetFingerprint,
		&i.CredentialKeyVersion,
		&i.CredentialWrappedDek,
		&i.CredentialNonce,
		&i.CredentialCiphertext,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Version,
	)
	return i, err
}

const insertConnection = `-- name: InsertConnection :exec
insert into public.connections (
    id, organization_id, db_type, display_name, host, port, database_name,
    tls_mode, target_fingerprint,
    credential_key_version, credential_wrapped_dek, credential_nonce, credential_ciphertext,
    created_by, created_at, updated_at
) values (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9,
    $10, $11, $12, $13,
    $14, $15, $16
)
`

type InsertConnectionParams struct {
	ID                   pgtype.UUID
	OrganizationID       pgtype.UUID
	DbType               string
	DisplayName          string
	Host                 string
	Port                 int32
	DatabaseName         string
	TlsMode              string
	TargetFingerprint    string
	CredentialKeyVersion *int32
	CredentialWrappedDek []byte
	CredentialNonce      []byte
	CredentialCiphertext []byte
	CreatedBy            pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) InsertConnection(ctx context.Context, arg InsertConnectionParams) error {
	_, err := q.db.Exec(ctx, insertConnection,
		arg.ID,
		arg.OrganizationID,
		arg.DbType,
		arg.DisplayName,
		arg.Host,
		arg.Port,
		arg.DatabaseName,
		arg.TlsMode,
		arg.TargetFingerprint,
		arg.CredentialKeyVersion,
		arg.CredentialWrappedDek,
		arg.CredentialNonce,
		arg.CredentialCiphertext,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listConnections = `-- name: ListConnections :many
select id, organization_id, db_type, display_name, host, port, database_name, tls_mode, target_fingerprint, credential_key_version, credential_wrapped_dek, credential_nonce, credential_ciphertext, created_by, created_at, updated_at, archived_at, version from public.connections
where organization_id = $1
  and ($2::boolean or archived_at is null)
order by created_at desc, id desc
`

type ListConnectionsParams struct {
	OrganizationID  pgtype.UUID
	IncludeArchived bool
}

func (q *Queries) ListConnections(ctx context.Context, arg ListConnectionsParams) ([]Connection, error) {
	rows, err := q.db.Query(ctx, listConnections, arg.OrganizationID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DbType,
			&i.DisplayName,
			&i.Host,
			&i.Port,
			&i.DatabaseName,
			&i.TlsMode,
			&i.TargetFingerprint,
			&i.CredentialKeyVersion,
			&i.CredentialWrappedDek,
			&i.CredentialNonce,
			&i.CredentialCiphertext,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameConnection = `-- name: RenameConnection :one
update public.connections
set display_name = $3, updated_at = now(), version = version + 1
where id = $1 and organization_id = $2
returning id, organization_id, db_type, display_name, host, port, database_name, tls_mode, target_fingerprint, credential_key_version, credential_wrapped_dek, credential_nonce, credential_ciphertext, created_by, created_at, updated_at, archived_at, version
`

type RenameConnectionParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	DisplayName    string
}

// Archived rows stay renameable: the name labels history, not the live target.
func (q *Queries) RenameConnection(ctx context.Context, arg RenameConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, renameConnection, arg.ID, arg.OrganizationID, arg.DisplayName)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DbType,
		&i.DisplayName,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.TlsMode,
		&i.TargetFingerprint,
		&i.CredentialKeyVersion,
		&i.CredentialWrappedDek,
		&i.CredentialNonce,
		&i.CredentialCiphertext,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Version,
	)
	return i, err
}

const replaceConnectionConfig = `-- name: ReplaceConnectionConfig :one
update public.connections
set display_name = $3, host = $4, port = $5, database_name = $6, tls_mode = $7,
    target_fingerprint = $8,
    credential_key_version = $9, credential_wrapped_dek = $10,
    credential_nonce = $11, credential_ciphertext = $12,
    updated_at = now(), version = version + 1
where id = $1 and organization_id = $2 and archived_at is null
  and version = $13
returning id, organization_id, db_type, display_name, host, port, database_name, tls_mode, target_fingerprint, credential_key_version, credential_wrapped_dek, credential_nonce, credential_ciphertext, created_by, created_at, updated_at, archived_at, version
`

type ReplaceConnectionConfigParams struct {
	ID                   pgtype.UUID
	OrganizationID       pgtype.UUID
	DisplayName          string
	Host                 string
	Port                 int32
	DatabaseName         string
	TlsMode              string
	TargetFingerprint    string
	CredentialKeyVersion *int32
	CredentialWrappedDek []byte
	CredentialNonce      []byte
	CredentialCiphertext []byte
	ExpectedVersion      int64
}

// Full config replacement (ADR-0014: no partial credential edit). Archived
// rows are excluded — restore is a separate future flow; the store
// disambiguates "missing" from "archived" on a zero rowcount.
func (q *Queries) ReplaceConnectionConfig(ctx context.Context, arg ReplaceConnectionConfigParams) (Connection, error) {
	row := q.db.QueryRow(ctx, replaceConnectionConfig,
		arg.ID,
		arg.OrganizationID,
		arg.DisplayName,
		arg.Host,
		arg.Port,
		arg.DatabaseName,
		arg.TlsMode,
		arg.TargetFingerprint,
		arg.CredentialKeyVersion,
		arg.CredentialWrappedDek,
		arg.CredentialNonce,
		arg.CredentialCiphertext,
		arg.ExpectedVersion,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DbType,
		&i.DisplayName,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.TlsMode,
		&i.TargetFingerprint,
		&i.CredentialKeyVersion,
		&i.CredentialWrappedDek,
		&i.CredentialNonce,
		&i.CredentialCiphertext,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Version,
	)
	return i, err
}
