// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connection_policies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpConnectionPolicyVersion = `-- name: BumpConnectionPolicyVersion :one
update public.connections
set current_policy_version = $3::bigint + 1
where id = $1 and organization_id = $2 and archived_at is null
  and current_policy_version = $3::bigint
returning id, organization_id, db_type, display_name, host, port, database_name, tls_mode, target_fingerprint, credential_key_version, credential_wrapped_dek, credential_nonce, credential_ciphertext, created_by, created_at, updated_at, archived_at, version, environment, description, current_policy_version, config_version
`

type BumpConnectionPolicyVersionParams struct {
	ID              pgtype.UUID
	OrganizationID  pgtype.UUID
	ExpectedVersion int64
}

// The optimistic pointer bump (ADR-0015): succeeds only when the caller's expected version is still current and the connection is active. Zero rows → the store disambiguates missing/archived/conflict. connections.version (the descriptor token) and updated_at are deliberately untouched — policy and descriptor concurrency are orthogonal.
func (q *Queries) BumpConnectionPolicyVersion(ctx context.Context, arg BumpConnectionPolicyVersionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, bumpConnectionPolicyVersion, arg.ID, arg.OrganizationID, arg.ExpectedVersion)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DbType,
		&i.DisplayName,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.TlsMode,
		&i.TargetFingerprint,
		&i.CredentialKeyVersion,
		&i.CredentialWrappedDek,
		&i.CredentialNonce,
		&i.CredentialCiphertext,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Version,
		&i.Environment,
		&i.Description,
		&i.CurrentPolicyVersion,
		&i.ConfigVersion,
	)
	return i, err
}

const getCurrentConnectionPolicy = `-- name: GetCurrentConnectionPolicy :one
select p.connection_id, p.organization_id, p.version, p.read_allowed, p.write_allowed, p.ddl_allowed, p.read_required_approvals, p.write_required_approvals, p.ddl_required_approvals, p.query_timeout_seconds, p.max_rows, p.max_result_bytes, p.created_by, p.created_at from public.connection_policy_versions p
join public.connections c
  on c.id = p.connection_id and c.current_policy_version = p.version
where c.id = $1 and c.organization_id = $2
`

type GetCurrentConnectionPolicyParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

// The connection's current policy snapshot, resolved through the pointer. Works for archived connections too: the policy is part of the historical snapshot (ADR-0015).
func (q *Queries) GetCurrentConnectionPolicy(ctx context.Context, arg GetCurrentConnectionPolicyParams) (ConnectionPolicyVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentConnectionPolicy, arg.ID, arg.OrganizationID)
	var i ConnectionPolicyVersion
	err := row.Scan(
		&i.ConnectionID,
		&i.OrganizationID,
		&i.Version,
		&i.ReadAllowed,
		&i.WriteAllowed,
		&i.DdlAllowed,
		&i.ReadRequiredApprovals,
		&i.WriteRequiredApprovals,
		&i.DdlRequiredApprovals,
		&i.QueryTimeoutSeconds,
		&i.MaxRows,
		&i.MaxResultBytes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertConnectionPolicyVersion = `-- name: InsertConnectionPolicyVersion :exec
insert into public.connection_policy_versions (
    connection_id, organization_id, version,
    read_allowed, write_allowed, ddl_allowed,
    read_required_approvals, write_required_approvals, ddl_required_approvals,
    query_timeout_seconds, max_rows, max_result_bytes,
    created_by, created_at
) values (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    -- Read the database clock after acquiring mutation locks so rows and audit events follow execution order; now() and inline clock_timestamp() can predate lock waits (ADR-0009). wait — named @at so the contract is visible here and not only in the store (ADR-0009). The caller's own created_at is domain-validation input.
    $13, $14::timestamptz
)
`

type InsertConnectionPolicyVersionParams struct {
	ConnectionID           pgtype.UUID
	OrganizationID         pgtype.UUID
	Version                int64
	ReadAllowed            bool
	WriteAllowed           bool
	DdlAllowed             bool
	ReadRequiredApprovals  int32
	WriteRequiredApprovals int32
	DdlRequiredApprovals   int32
	QueryTimeoutSeconds    int32
	MaxRows                int32
	MaxResultBytes         int64
	CreatedBy              pgtype.UUID
	At                     pgtype.Timestamptz
}

// Append-only: a policy update inserts version N+1 (the (connection_id, version) PK is the structural guard against duplicates); rows are never updated (runtime UPDATE is revoked — ADR-0015).
func (q *Queries) InsertConnectionPolicyVersion(ctx context.Context, arg InsertConnectionPolicyVersionParams) error {
	_, err := q.db.Exec(ctx, insertConnectionPolicyVersion,
		arg.ConnectionID,
		arg.OrganizationID,
		arg.Version,
		arg.ReadAllowed,
		arg.WriteAllowed,
		arg.DdlAllowed,
		arg.ReadRequiredApprovals,
		arg.WriteRequiredApprovals,
		arg.DdlRequiredApprovals,
		arg.QueryTimeoutSeconds,
		arg.MaxRows,
		arg.MaxResultBytes,
		arg.CreatedBy,
		arg.At,
	)
	return err
}
