// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertResultChunks implements pgx.CopyFromSource.
type iteratorForInsertResultChunks struct {
	rows                 []InsertResultChunksParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertResultChunks) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertResultChunks) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ResultID,
		r.rows[0].OrganizationID,
		r.rows[0].ChunkIndex,
		r.rows[0].Nonce,
		r.rows[0].Ciphertext,
	}, nil
}

func (r iteratorForInsertResultChunks) Err() error {
	return nil
}

func (q *Queries) InsertResultChunks(ctx context.Context, arg []InsertResultChunksParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"result_cache", "result_chunks"}, []string{"result_id", "organization_id", "chunk_index", "nonce", "ciphertext"}, &iteratorForInsertResultChunks{rows: arg})
}
