// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: executions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finishQueryExecution = `-- name: FinishQueryExecution :execrows
update public.query_executions
set outcome = $1, finished_at = $2::timestamptz,
    rows_affected = $3, duration_ms = $4,
    result_id = $5, result_expires_at = $6,
    row_count = $7, byte_count = $8, truncated = $9
where request_id = $10 and organization_id = $11
  and owner = $12 and attempt_id = $13 and outcome is null
`

type FinishQueryExecutionParams struct {
	Outcome         *string
	At              pgtype.Timestamptz
	RowsAffected    int64
	DurationMs      int64
	ResultID        pgtype.UUID
	ResultExpiresAt pgtype.Timestamptz
	RowCount        int64
	ByteCount       int64
	Truncated       bool
	RequestID       pgtype.UUID
	OrganizationID  pgtype.UUID
	Owner           string
	AttemptID       pgtype.UUID
}

func (q *Queries) FinishQueryExecution(ctx context.Context, arg FinishQueryExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishQueryExecution,
		arg.Outcome,
		arg.At,
		arg.RowsAffected,
		arg.DurationMs,
		arg.ResultID,
		arg.ResultExpiresAt,
		arg.RowCount,
		arg.ByteCount,
		arg.Truncated,
		arg.RequestID,
		arg.OrganizationID,
		arg.Owner,
		arg.AttemptID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getQueryExecution = `-- name: GetQueryExecution :one
select request_id, organization_id, owner, attempt_id, heartbeat, deadline, started_at, finished_at, outcome, rows_affected, duration_ms, result_id, result_expires_at, row_count, byte_count, truncated from public.query_executions
where request_id = $1 and organization_id = $2
`

type GetQueryExecutionParams struct {
	RequestID      pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) GetQueryExecution(ctx context.Context, arg GetQueryExecutionParams) (QueryExecution, error) {
	row := q.db.QueryRow(ctx, getQueryExecution, arg.RequestID, arg.OrganizationID)
	var i QueryExecution
	err := row.Scan(
		&i.RequestID,
		&i.OrganizationID,
		&i.Owner,
		&i.AttemptID,
		&i.Heartbeat,
		&i.Deadline,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Outcome,
		&i.RowsAffected,
		&i.DurationMs,
		&i.ResultID,
		&i.ResultExpiresAt,
		&i.RowCount,
		&i.ByteCount,
		&i.Truncated,
	)
	return i, err
}

const heartbeatQueryExecution = `-- name: HeartbeatQueryExecution :execrows
update public.query_executions set heartbeat = $1::timestamptz, deadline = $1::timestamptz + interval '60 seconds'
where request_id = $2 and organization_id = $3
  and owner = $4 and attempt_id = $5 and outcome is null
  and deadline > $1::timestamptz
`

type HeartbeatQueryExecutionParams struct {
	At             pgtype.Timestamptz
	RequestID      pgtype.UUID
	OrganizationID pgtype.UUID
	Owner          string
	AttemptID      pgtype.UUID
}

func (q *Queries) HeartbeatQueryExecution(ctx context.Context, arg HeartbeatQueryExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatQueryExecution,
		arg.At,
		arg.RequestID,
		arg.OrganizationID,
		arg.Owner,
		arg.AttemptID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertQueryExecution = `-- name: InsertQueryExecution :one
with stamp as (select $5::timestamptz as at)
insert into public.query_executions (request_id, organization_id, owner, attempt_id, heartbeat, deadline, started_at)
select $1, $2, $3, $4, stamp.at, stamp.at + interval '60 seconds', stamp.at from stamp
returning request_id, organization_id, owner, attempt_id, heartbeat, deadline, started_at, finished_at, outcome, rows_affected, duration_ms, result_id, result_expires_at, row_count, byte_count, truncated
`

type InsertQueryExecutionParams struct {
	RequestID      pgtype.UUID
	OrganizationID pgtype.UUID
	Owner          string
	AttemptID      pgtype.UUID
	At             pgtype.Timestamptz
}

func (q *Queries) InsertQueryExecution(ctx context.Context, arg InsertQueryExecutionParams) (QueryExecution, error) {
	row := q.db.QueryRow(ctx, insertQueryExecution,
		arg.RequestID,
		arg.OrganizationID,
		arg.Owner,
		arg.AttemptID,
		arg.At,
	)
	var i QueryExecution
	err := row.Scan(
		&i.RequestID,
		&i.OrganizationID,
		&i.Owner,
		&i.AttemptID,
		&i.Heartbeat,
		&i.Deadline,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Outcome,
		&i.RowsAffected,
		&i.DurationMs,
		&i.ResultID,
		&i.ResultExpiresAt,
		&i.RowCount,
		&i.ByteCount,
		&i.Truncated,
	)
	return i, err
}

const listOverdueExecutions = `-- name: ListOverdueExecutions :many
select request_id from public.query_executions
where organization_id = $1 and outcome is null and deadline <= clock_timestamp()
order by request_id limit 100
`

func (q *Queries) ListOverdueExecutions(ctx context.Context, organizationID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listOverdueExecutions, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var request_id pgtype.UUID
		if err := rows.Scan(&request_id); err != nil {
			return nil, err
		}
		items = append(items, request_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockQueryExecution = `-- name: LockQueryExecution :one
select request_id, organization_id, owner, attempt_id, heartbeat, deadline, started_at, finished_at, outcome, rows_affected, duration_ms, result_id, result_expires_at, row_count, byte_count, truncated from public.query_executions
where request_id = $1 and organization_id = $2
for update
`

type LockQueryExecutionParams struct {
	RequestID      pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) LockQueryExecution(ctx context.Context, arg LockQueryExecutionParams) (QueryExecution, error) {
	row := q.db.QueryRow(ctx, lockQueryExecution, arg.RequestID, arg.OrganizationID)
	var i QueryExecution
	err := row.Scan(
		&i.RequestID,
		&i.OrganizationID,
		&i.Owner,
		&i.AttemptID,
		&i.Heartbeat,
		&i.Deadline,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Outcome,
		&i.RowsAffected,
		&i.DurationMs,
		&i.ResultID,
		&i.ResultExpiresAt,
		&i.RowCount,
		&i.ByteCount,
		&i.Truncated,
	)
	return i, err
}
