// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: executions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finishQueryExecution = `-- name: FinishQueryExecution :execrows
update public.query_executions
set outcome = $1, finished_at = $2::timestamptz,
    rows_affected = $3, duration_ms = $4,
    result_id = $5, result_expires_at = $6,
    row_count = $7, byte_count = $8, truncated = $9
where request_id = $10 and organization_id = $11
  and owner = $12 and attempt_id = $13 and outcome is null
`

type FinishQueryExecutionParams struct {
	Outcome         *string
	At              pgtype.Timestamptz
	RowsAffected    int64
	DurationMs      int64
	ResultID        pgtype.UUID
	ResultExpiresAt pgtype.Timestamptz
	RowCount        int64
	ByteCount       int64
	Truncated       bool
	RequestID       pgtype.UUID
	OrganizationID  pgtype.UUID
	Owner           string
	AttemptID       pgtype.UUID
}

func (q *Queries) FinishQueryExecution(ctx context.Context, arg FinishQueryExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishQueryExecution,
		arg.Outcome,
		arg.At,
		arg.RowsAffected,
		arg.DurationMs,
		arg.ResultID,
		arg.ResultExpiresAt,
		arg.RowCount,
		arg.ByteCount,
		arg.Truncated,
		arg.RequestID,
		arg.OrganizationID,
		arg.Owner,
		arg.AttemptID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getQueryExecution = `-- name: GetQueryExecution :one
select request_id, organization_id, owner, attempt_id, heartbeat, deadline, started_at, finished_at, outcome, rows_affected, duration_ms, result_id, result_expires_at, row_count, byte_count, truncated from public.query_executions
where request_id = $1 and organization_id = $2
`

type GetQueryExecutionParams struct {
	RequestID      pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) GetQueryExecution(ctx context.Context, arg GetQueryExecutionParams) (QueryExecution, error) {
	row := q.db.QueryRow(ctx, getQueryExecution, arg.RequestID, arg.OrganizationID)
	var i QueryExecution
	err := row.Scan(
		&i.RequestID,
		&i.OrganizationID,
		&i.Owner,
		&i.AttemptID,
		&i.Heartbeat,
		&i.Deadline,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Outcome,
		&i.RowsAffected,
		&i.DurationMs,
		&i.ResultID,
		&i.ResultExpiresAt,
		&i.RowCount,
		&i.ByteCount,
		&i.Truncated,
	)
	return i, err
}

const heartbeatQueryExecution = `-- name: HeartbeatQueryExecution :execrows
update public.query_executions set heartbeat = $1::timestamptz, deadline = $1::timestamptz + $2::bigint * interval '1 millisecond'
where request_id = $3 and organization_id = $4
  and owner = $5 and attempt_id = $6 and outcome is null
  and deadline > $1::timestamptz
`

type HeartbeatQueryExecutionParams struct {
	At                pgtype.Timestamptz
	LeaseMilliseconds int64
	RequestID         pgtype.UUID
	OrganizationID    pgtype.UUID
	Owner             string
	AttemptID         pgtype.UUID
}

func (q *Queries) HeartbeatQueryExecution(ctx context.Context, arg HeartbeatQueryExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatQueryExecution,
		arg.At,
		arg.LeaseMilliseconds,
		arg.RequestID,
		arg.OrganizationID,
		arg.Owner,
		arg.AttemptID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertQueryExecution = `-- name: InsertQueryExecution :one
with stamp as (select $6::timestamptz as at)
insert into public.query_executions (request_id, organization_id, owner, attempt_id, heartbeat, deadline, started_at)
select $1, $2, $3, $4, stamp.at, stamp.at + $5::bigint * interval '1 millisecond', stamp.at from stamp
returning request_id, organization_id, owner, attempt_id, heartbeat, deadline, started_at, finished_at, outcome, rows_affected, duration_ms, result_id, result_expires_at, row_count, byte_count, truncated
`

type InsertQueryExecutionParams struct {
	RequestID         pgtype.UUID
	OrganizationID    pgtype.UUID
	Owner             string
	AttemptID         pgtype.UUID
	LeaseMilliseconds int64
	At                pgtype.Timestamptz
}

func (q *Queries) InsertQueryExecution(ctx context.Context, arg InsertQueryExecutionParams) (QueryExecution, error) {
	row := q.db.QueryRow(ctx, insertQueryExecution,
		arg.RequestID,
		arg.OrganizationID,
		arg.Owner,
		arg.AttemptID,
		arg.LeaseMilliseconds,
		arg.At,
	)
	var i QueryExecution
	err := row.Scan(
		&i.RequestID,
		&i.OrganizationID,
		&i.Owner,
		&i.AttemptID,
		&i.Heartbeat,
		&i.Deadline,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Outcome,
		&i.RowsAffected,
		&i.DurationMs,
		&i.ResultID,
		&i.ResultExpiresAt,
		&i.RowCount,
		&i.ByteCount,
		&i.Truncated,
	)
	return i, err
}

const listOverdueExecutions = `-- name: ListOverdueExecutions :many
select request_id, deadline from public.query_executions
where organization_id = $1 and outcome is null and deadline <= clock_timestamp()
  and ($2::timestamptz is null
       or (deadline, request_id) > ($2::timestamptz, $3::uuid))
order by deadline, request_id limit $4::int
`

type ListOverdueExecutionsParams struct {
	OrganizationID pgtype.UUID
	AfterDeadline  pgtype.Timestamptz
	AfterRequestID pgtype.UUID
	BatchSize      int32
}

type ListOverdueExecutionsRow struct {
	RequestID pgtype.UUID
	Deadline  pgtype.Timestamptz
}

// Keyset pagination by (deadline, request_id) lets a run page past an attempt whose recovery keeps failing.
func (q *Queries) ListOverdueExecutions(ctx context.Context, arg ListOverdueExecutionsParams) ([]ListOverdueExecutionsRow, error) {
	rows, err := q.db.Query(ctx, listOverdueExecutions,
		arg.OrganizationID,
		arg.AfterDeadline,
		arg.AfterRequestID,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverdueExecutionsRow{}
	for rows.Next() {
		var i ListOverdueExecutionsRow
		if err := rows.Scan(&i.RequestID, &i.Deadline); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccessRequestSkipLocked = `-- name: LockAccessRequestSkipLocked :one
select id, organization_id, connection_id, requester_id, state, state_reason, payload_key_version, payload_wrapped_dek, payload_nonce, payload_ciphertext, payload_digest, payload_digest_key_version, redacted_sql, statement_class, policy_version, required_approvals, submitted_at, connection_config_version, connection_fingerprint, connection_display_name, connection_db_type, expires_at, version, created_at, updated_at, title from public.access_requests
where id = $1 and organization_id = $2
for update skip locked
`

type LockAccessRequestSkipLockedParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

// Reconciliation skips a request that a completing owner or another replica holds instead of waiting behind it.
func (q *Queries) LockAccessRequestSkipLocked(ctx context.Context, arg LockAccessRequestSkipLockedParams) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, lockAccessRequestSkipLocked, arg.ID, arg.OrganizationID)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ConnectionID,
		&i.RequesterID,
		&i.State,
		&i.StateReason,
		&i.PayloadKeyVersion,
		&i.PayloadWrappedDek,
		&i.PayloadNonce,
		&i.PayloadCiphertext,
		&i.PayloadDigest,
		&i.PayloadDigestKeyVersion,
		&i.RedactedSql,
		&i.StatementClass,
		&i.PolicyVersion,
		&i.RequiredApprovals,
		&i.SubmittedAt,
		&i.ConnectionConfigVersion,
		&i.ConnectionFingerprint,
		&i.ConnectionDisplayName,
		&i.ConnectionDbType,
		&i.ExpiresAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
	)
	return i, err
}

const lockQueryExecution = `-- name: LockQueryExecution :one
select request_id, organization_id, owner, attempt_id, heartbeat, deadline, started_at, finished_at, outcome, rows_affected, duration_ms, result_id, result_expires_at, row_count, byte_count, truncated from public.query_executions
where request_id = $1 and organization_id = $2
for update
`

type LockQueryExecutionParams struct {
	RequestID      pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) LockQueryExecution(ctx context.Context, arg LockQueryExecutionParams) (QueryExecution, error) {
	row := q.db.QueryRow(ctx, lockQueryExecution, arg.RequestID, arg.OrganizationID)
	var i QueryExecution
	err := row.Scan(
		&i.RequestID,
		&i.OrganizationID,
		&i.Owner,
		&i.AttemptID,
		&i.Heartbeat,
		&i.Deadline,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Outcome,
		&i.RowsAffected,
		&i.DurationMs,
		&i.ResultID,
		&i.ResultExpiresAt,
		&i.RowCount,
		&i.ByteCount,
		&i.Truncated,
	)
	return i, err
}
