// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
select count(*) from public.users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
insert into public.organization_memberships (organization_id, user_id, role_id)
values ($1, $2, $3)
returning id, organization_id, user_id, created_at, role_id
`

type CreateMembershipParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	RoleID         pgtype.UUID
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.OrganizationID, arg.UserID, arg.RoleID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.CreatedAt,
		&i.RoleID,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
insert into public.sessions (user_id, token_hash, idle_expires_at, absolute_expires_at)
values ($1, $2, $3, $4)
returning id, user_id, token_hash, idle_expires_at, absolute_expires_at, revoked_at, created_at
`

type CreateSessionParams struct {
	UserID            pgtype.UUID
	TokenHash         []byte
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into public.users (email, display_name)
values ($1, $2)
returning id, email, display_name, status, created_at
`

type CreateUserParams struct {
	Email       string
	DisplayName string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const extendSessionIdle = `-- name: ExtendSessionIdle :execrows
update public.sessions
set idle_expires_at = least(greatest(idle_expires_at, $1), absolute_expires_at)
where id = $2
  and revoked_at is null
  and idle_expires_at > clock_timestamp()
  and absolute_expires_at > clock_timestamp()
`

type ExtendSessionIdleParams struct {
	IdleExpiresAt pgtype.Timestamptz
	ID            pgtype.UUID
}

// Check expiry with clock_timestamp() after lock waits, then extend idle expiry monotonically within absolute expiry; now() could resurrect an expired session.
func (q *Queries) ExtendSessionIdle(ctx context.Context, arg ExtendSessionIdleParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendSessionIdle, arg.IdleExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDefaultOrganization = `-- name: GetDefaultOrganization :one
select id, name, slug, created_at from public.organizations where slug = 'default'
`

func (q *Queries) GetDefaultOrganization(ctx context.Context) (Organization, error) {
	row := q.db.QueryRow(ctx, getDefaultOrganization)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
select id, organization_id, user_id, created_at, role_id from public.organization_memberships
where organization_id = $1 and user_id = $2
`

type GetMembershipParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.OrganizationID, arg.UserID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.CreatedAt,
		&i.RoleID,
	)
	return i, err
}

const getPasswordAuth = `-- name: GetPasswordAuth :one
select id, user_id, type, secret, created_at, updated_at from public.auth_methods where user_id = $1 and type = 'password'
`

func (q *Queries) GetPasswordAuth(ctx context.Context, userID pgtype.UUID) (AuthMethod, error) {
	row := q.db.QueryRow(ctx, getPasswordAuth, userID)
	var i AuthMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Secret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
select id, user_id, token_hash, idle_expires_at, absolute_expires_at, revoked_at, created_at from public.sessions where token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, display_name, status, created_at from public.users where lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, email, display_name, status, created_at from public.users where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserForLogin = `-- name: GetUserForLogin :one
select u.id, u.email, u.display_name, u.status, u.created_at, coalesce(am.secret, '') as password_hash,
       coalesce(lb.failure_count, 0) as failure_count,
       lb.locked_until,
       (lb.locked_until is not null and lb.locked_until > now())::boolean as locked
from public.users u
left join public.auth_methods am on am.user_id = u.id and am.type = 'password'
left join public.login_backoff lb on lb.user_id = u.id
where lower(u.email) = lower($1)
`

type GetUserForLoginRow struct {
	ID           pgtype.UUID
	Email        string
	DisplayName  string
	Status       string
	CreatedAt    pgtype.Timestamptz
	PasswordHash string
	FailureCount int32
	LockedUntil  pgtype.Timestamptz
	Locked       bool
}

// Read identity, password hash, and lockout together so known and unknown accounts use one lookup. Evaluate lockout on the same database clock as failure writes.
func (q *Queries) GetUserForLogin(ctx context.Context, lower string) (GetUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, lower)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.FailureCount,
		&i.LockedUntil,
		&i.Locked,
	)
	return i, err
}

const listOrganizationIDs = `-- name: ListOrganizationIDs :many
select id from public.organizations order by id
`

// Administrative identity-only enumeration for per-organization maintenance; every org-scoped read still filters by one organization (ADR-0004).
func (q *Queries) ListOrganizationIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listOrganizationIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLoginFailure = `-- name: RecordLoginFailure :one
insert into public.login_backoff (user_id, failure_count, locked_until, last_failure_at)
values (
    $1, 1,
    case when 1 >= $2::int then
        now() + make_interval(secs =>
            least($3::float8, $4::float8)
            * $5::float8)
    end,
    now()
)
on conflict (user_id) do update set
    failure_count = case
        when (login_backoff.locked_until is not null and login_backoff.locked_until <= now())
          or (login_backoff.locked_until is null and login_backoff.last_failure_at <= now() - make_interval(secs => $6::float8))
        then 1 else login_backoff.failure_count + 1 end,
    locked_until = case
        when (case
                when (login_backoff.locked_until is not null and login_backoff.locked_until <= now())
                  or (login_backoff.locked_until is null and login_backoff.last_failure_at <= now() - make_interval(secs => $6::float8))
                then 1 else login_backoff.failure_count + 1 end) >= $2::int
        then greatest(
            coalesce(case when login_backoff.locked_until > now() then login_backoff.locked_until end, '-infinity'::timestamptz),
            now() + make_interval(secs =>
                least(
                    $3::float8 * pow(2, least(greatest(
                        (case
                            when (login_backoff.locked_until is not null and login_backoff.locked_until <= now())
                              or (login_backoff.locked_until is null and login_backoff.last_failure_at <= now() - make_interval(secs => $6::float8))
                            then 1 else login_backoff.failure_count + 1 end) - $2::int, 0), 30)),
                    $4::float8)
                * $5::float8))
        else null end,
    last_failure_at = now()
returning failure_count, locked_until,
    (locked_until is not null and locked_until > now())::boolean as locked
`

type RecordLoginFailureParams struct {
	UserID        pgtype.UUID
	Threshold     int32
	BaseSecs      float64
	CapSecs       float64
	JitterFactor  float64
	StalenessSecs float64
}

type RecordLoginFailureRow struct {
	FailureCount int32
	LockedUntil  pgtype.Timestamptz
	Locked       bool
}

// Atomically count failure and extend jittered lockout on the database clock. Expired/stale counters restart; clamped exponents prevent overflow and greatest() prevents shorter expiry.
func (q *Queries) RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) (RecordLoginFailureRow, error) {
	row := q.db.QueryRow(ctx, recordLoginFailure,
		arg.UserID,
		arg.Threshold,
		arg.BaseSecs,
		arg.CapSecs,
		arg.JitterFactor,
		arg.StalenessSecs,
	)
	var i RecordLoginFailureRow
	err := row.Scan(&i.FailureCount, &i.LockedUntil, &i.Locked)
	return i, err
}

const resetLoginBackoff = `-- name: ResetLoginBackoff :exec
update public.login_backoff
set failure_count = 0, locked_until = null
where user_id = $1 and (failure_count > 0 or locked_until is not null)
`

// A successful login clears the slate. The WHERE leaves an already-clean row unwritten, so calling this on every success keeps the hot path write-free while still clearing failures committed by concurrent attempts mid-verify.
func (q *Queries) ResetLoginBackoff(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetLoginBackoff, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :execrows
update public.sessions set revoked_at = now()
where id = $1 and revoked_at is null
`

// Only an ACTIVE session revokes: re-revoking (a concurrent double logout) must not overwrite the original revoked_at — forensic evidence of WHEN the session actually died — and the caller skips the audit event when no row changed, so the trail records only real state changes (ADR-0009).
func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
update public.sessions set revoked_at = now()
where user_id = $1 and revoked_at is null
`

// Invalidate a user's active sessions (ADR-0006: login/privilege change rotates).
func (q *Queries) RevokeUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const upsertPasswordAuth = `-- name: UpsertPasswordAuth :exec
insert into public.auth_methods (user_id, type, secret)
values ($1, 'password', $2)
on conflict (user_id, type)
do update set secret = excluded.secret, updated_at = now()
`

type UpsertPasswordAuthParams struct {
	UserID pgtype.UUID
	Secret string
}

func (q *Queries) UpsertPasswordAuth(ctx context.Context, arg UpsertPasswordAuthParams) error {
	_, err := q.db.Exec(ctx, upsertPasswordAuth, arg.UserID, arg.Secret)
	return err
}

const validateSession = `-- name: ValidateSession :one
select true from public.sessions
where id = $1
  and revoked_at is null
  and idle_expires_at > now()
  and absolute_expires_at > now()
`

// Final post-CSRF validity check for a request whose idle slide is throttled. It deliberately does not write, but its predicates use the database clock so a concurrently revoked or expired session cannot reach a handler.
func (q *Queries) ValidateSession(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, validateSession, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
