// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
select count(*) from users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
insert into organization_memberships (organization_id, user_id, role_id)
values ($1, $2, $3)
returning id, organization_id, user_id, created_at, role_id
`

type CreateMembershipParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	RoleID         pgtype.UUID
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.OrganizationID, arg.UserID, arg.RoleID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.CreatedAt,
		&i.RoleID,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
insert into sessions (user_id, token_hash, idle_expires_at, absolute_expires_at)
values ($1, $2, $3, $4)
returning id, user_id, token_hash, idle_expires_at, absolute_expires_at, revoked_at, created_at
`

type CreateSessionParams struct {
	UserID            pgtype.UUID
	TokenHash         []byte
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into users (email, display_name)
values ($1, $2)
returning id, email, display_name, status, created_at
`

type CreateUserParams struct {
	Email       string
	DisplayName string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const extendSessionIdle = `-- name: ExtendSessionIdle :exec
update sessions
set idle_expires_at = least(greatest(idle_expires_at, $1), absolute_expires_at)
where id = $2 and revoked_at is null
`

type ExtendSessionIdleParams struct {
	IdleExpiresAt pgtype.Timestamptz
	ID            pgtype.UUID
}

// Slide the idle window forward on activity, never past the absolute expiry and
// never backward (greatest() guards against a late, older request regressing it).
func (q *Queries) ExtendSessionIdle(ctx context.Context, arg ExtendSessionIdleParams) error {
	_, err := q.db.Exec(ctx, extendSessionIdle, arg.IdleExpiresAt, arg.ID)
	return err
}

const getDefaultOrganization = `-- name: GetDefaultOrganization :one
select id, name, slug, created_at from organizations where slug = 'default'
`

func (q *Queries) GetDefaultOrganization(ctx context.Context) (Organization, error) {
	row := q.db.QueryRow(ctx, getDefaultOrganization)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
select id, organization_id, user_id, created_at, role_id from organization_memberships
where organization_id = $1 and user_id = $2
`

type GetMembershipParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.OrganizationID, arg.UserID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.CreatedAt,
		&i.RoleID,
	)
	return i, err
}

const getPasswordAuth = `-- name: GetPasswordAuth :one
select id, user_id, type, secret, created_at, updated_at from auth_methods where user_id = $1 and type = 'password'
`

func (q *Queries) GetPasswordAuth(ctx context.Context, userID pgtype.UUID) (AuthMethod, error) {
	row := q.db.QueryRow(ctx, getPasswordAuth, userID)
	var i AuthMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Secret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
select id, user_id, token_hash, idle_expires_at, absolute_expires_at, revoked_at, created_at from sessions where token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, display_name, status, created_at from users where lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, email, display_name, status, created_at from users where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
update sessions set revoked_at = now() where id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const upsertPasswordAuth = `-- name: UpsertPasswordAuth :exec
insert into auth_methods (user_id, type, secret)
values ($1, 'password', $2)
on conflict (user_id, type)
do update set secret = excluded.secret, updated_at = now()
`

type UpsertPasswordAuthParams struct {
	UserID pgtype.UUID
	Secret string
}

func (q *Queries) UpsertPasswordAuth(ctx context.Context, arg UpsertPasswordAuthParams) error {
	_, err := q.db.Exec(ctx, upsertPasswordAuth, arg.UserID, arg.Secret)
	return err
}
