// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: key_rotation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const lockRotationCredentials = `-- name: LockRotationCredentials :many
select id,organization_id,credential_key_version,credential_wrapped_dek,credential_nonce,credential_ciphertext
from public.connections where organization_id=$1 and credential_key_version < $2::int
order by id limit 100 for update
`

type LockRotationCredentialsParams struct {
	OrganizationID pgtype.UUID
	ActiveVersion  int32
}

type LockRotationCredentialsRow struct {
	ID                   pgtype.UUID
	OrganizationID       pgtype.UUID
	CredentialKeyVersion *int32
	CredentialWrappedDek []byte
	CredentialNonce      []byte
	CredentialCiphertext []byte
}

func (q *Queries) LockRotationCredentials(ctx context.Context, arg LockRotationCredentialsParams) ([]LockRotationCredentialsRow, error) {
	rows, err := q.db.Query(ctx, lockRotationCredentials, arg.OrganizationID, arg.ActiveVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockRotationCredentialsRow{}
	for rows.Next() {
		var i LockRotationCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CredentialKeyVersion,
			&i.CredentialWrappedDek,
			&i.CredentialNonce,
			&i.CredentialCiphertext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRotationPayloads = `-- name: LockRotationPayloads :many
select id,organization_id,payload_key_version,payload_wrapped_dek,payload_nonce,payload_ciphertext
from public.access_requests where organization_id=$1 and payload_key_version < $2::int
order by id limit 100 for update
`

type LockRotationPayloadsParams struct {
	OrganizationID pgtype.UUID
	ActiveVersion  int32
}

type LockRotationPayloadsRow struct {
	ID                pgtype.UUID
	OrganizationID    pgtype.UUID
	PayloadKeyVersion int32
	PayloadWrappedDek []byte
	PayloadNonce      []byte
	PayloadCiphertext []byte
}

func (q *Queries) LockRotationPayloads(ctx context.Context, arg LockRotationPayloadsParams) ([]LockRotationPayloadsRow, error) {
	rows, err := q.db.Query(ctx, lockRotationPayloads, arg.OrganizationID, arg.ActiveVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockRotationPayloadsRow{}
	for rows.Next() {
		var i LockRotationPayloadsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PayloadKeyVersion,
			&i.PayloadWrappedDek,
			&i.PayloadNonce,
			&i.PayloadCiphertext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRotationResultKeys = `-- name: LockRotationResultKeys :many
select id,organization_id,key_version,wrapped_dek from result_cache.result_sets
where organization_id=$1 and key_version < $2::int order by id limit 100 for update
`

type LockRotationResultKeysParams struct {
	OrganizationID pgtype.UUID
	ActiveVersion  int32
}

type LockRotationResultKeysRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	KeyVersion     int32
	WrappedDek     []byte
}

func (q *Queries) LockRotationResultKeys(ctx context.Context, arg LockRotationResultKeysParams) ([]LockRotationResultKeysRow, error) {
	rows, err := q.db.Query(ctx, lockRotationResultKeys, arg.OrganizationID, arg.ActiveVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockRotationResultKeysRow{}
	for rows.Next() {
		var i LockRotationResultKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.KeyVersion,
			&i.WrappedDek,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateCredentialEnvelope = `-- name: RotateCredentialEnvelope :exec
update public.connections set credential_key_version=$1,credential_wrapped_dek=$2,
credential_nonce=$3,credential_ciphertext=$4
where id=$5 and organization_id=$6
`

type RotateCredentialEnvelopeParams struct {
	KeyVersion     *int32
	WrappedDek     []byte
	Nonce          []byte
	Ciphertext     []byte
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) RotateCredentialEnvelope(ctx context.Context, arg RotateCredentialEnvelopeParams) error {
	_, err := q.db.Exec(ctx, rotateCredentialEnvelope,
		arg.KeyVersion,
		arg.WrappedDek,
		arg.Nonce,
		arg.Ciphertext,
		arg.ID,
		arg.OrganizationID,
	)
	return err
}

const rotatePayloadEnvelope = `-- name: RotatePayloadEnvelope :exec
update public.access_requests set payload_key_version=$1,payload_wrapped_dek=$2,
payload_nonce=$3,payload_ciphertext=$4
where id=$5 and organization_id=$6
`

type RotatePayloadEnvelopeParams struct {
	KeyVersion     int32
	WrappedDek     []byte
	Nonce          []byte
	Ciphertext     []byte
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) RotatePayloadEnvelope(ctx context.Context, arg RotatePayloadEnvelopeParams) error {
	_, err := q.db.Exec(ctx, rotatePayloadEnvelope,
		arg.KeyVersion,
		arg.WrappedDek,
		arg.Nonce,
		arg.Ciphertext,
		arg.ID,
		arg.OrganizationID,
	)
	return err
}

const rotateResultEnvelope = `-- name: RotateResultEnvelope :exec
update result_cache.result_sets set key_version=$1,wrapped_dek=$2
where id=$3 and organization_id=$4
`

type RotateResultEnvelopeParams struct {
	KeyVersion     int32
	WrappedDek     []byte
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) RotateResultEnvelope(ctx context.Context, arg RotateResultEnvelopeParams) error {
	_, err := q.db.Exec(ctx, rotateResultEnvelope,
		arg.KeyVersion,
		arg.WrappedDek,
		arg.ID,
		arg.OrganizationID,
	)
	return err
}
