// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessRequest struct {
	ID                      pgtype.UUID
	OrganizationID          pgtype.UUID
	ConnectionID            pgtype.UUID
	RequesterID             pgtype.UUID
	State                   string
	StateReason             *string
	PayloadKeyVersion       int32
	PayloadWrappedDek       []byte
	PayloadNonce            []byte
	PayloadCiphertext       []byte
	PayloadDigest           []byte
	PayloadDigestKeyVersion *int32
	RedactedSql             *string
	StatementClass          *string
	PolicyVersion           *int64
	RequiredApprovals       *int32
	SubmittedAt             pgtype.Timestamptz
	ConnectionConfigVersion *int64
	ConnectionFingerprint   *string
	ConnectionDisplayName   *string
	ConnectionDbType        *string
	ExpiresAt               pgtype.Timestamptz
	Version                 int64
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type Approval struct {
	ID             pgtype.UUID
	RequestID      pgtype.UUID
	OrganizationID pgtype.UUID
	ApproverID     pgtype.UUID
	Decision       string
	Reason         string
	DecidedAt      pgtype.Timestamptz
}

type AuditEvent struct {
	ID                      pgtype.UUID
	OrganizationID          pgtype.UUID
	OccurredAt              pgtype.Timestamptz
	ActorType               string
	ActorUserID             pgtype.UUID
	ActorService            *string
	Action                  string
	TargetType              string
	TargetID                *string
	Outcome                 string
	PreviousState           *string
	NextState               *string
	PayloadDigest           []byte
	PayloadDigestKeyVersion *int32
	RequestID               *string
	ConnectionID            pgtype.UUID
	QueryType               *string
	RowsAffected            *int64
	DurationMs              *int64
	RiskScore               *float64
	Metadata                []byte
}

type AuthMethod struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Type      string
	Secret    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Connection struct {
	ID                   pgtype.UUID
	OrganizationID       pgtype.UUID
	DbType               string
	DisplayName          string
	Host                 string
	Port                 int32
	DatabaseName         string
	TlsMode              string
	TargetFingerprint    string
	CredentialKeyVersion *int32
	CredentialWrappedDek []byte
	CredentialNonce      []byte
	CredentialCiphertext []byte
	CreatedBy            pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ArchivedAt           pgtype.Timestamptz
	Version              int64
	Environment          string
	Description          string
	CurrentPolicyVersion int64
	ConfigVersion        int64
}

type ConnectionPolicyVersion struct {
	ConnectionID           pgtype.UUID
	OrganizationID         pgtype.UUID
	Version                int64
	ReadAllowed            bool
	WriteAllowed           bool
	DdlAllowed             bool
	ReadRequiredApprovals  int32
	WriteRequiredApprovals int32
	DdlRequiredApprovals   int32
	QueryTimeoutSeconds    int32
	MaxRows                int32
	MaxResultBytes         int64
	CreatedBy              pgtype.UUID
	CreatedAt              pgtype.Timestamptz
}

type LoginBackoff struct {
	UserID        pgtype.UUID
	FailureCount  int32
	LockedUntil   pgtype.Timestamptz
	LastFailureAt pgtype.Timestamptz
}

type OidcIdentity struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Issuer    string
	Subject   string
	Email     string
	CreatedAt pgtype.Timestamptz
}

type Organization struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
}

type OrganizationMembership struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	RoleID         pgtype.UUID
}

type Permission struct {
	Key         string
	Description string
}

type QueryExecution struct {
	RequestID       pgtype.UUID
	OrganizationID  pgtype.UUID
	Owner           string
	AttemptID       pgtype.UUID
	Heartbeat       pgtype.Timestamptz
	Deadline        pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	Outcome         *string
	RowsAffected    int64
	DurationMs      int64
	ResultID        pgtype.UUID
	ResultExpiresAt pgtype.Timestamptz
	RowCount        int64
	ByteCount       int64
	Truncated       bool
}

type Role struct {
	ID                 pgtype.UUID
	OrganizationID     pgtype.UUID
	Name               string
	IsSystem           bool
	IsBootstrapDefault bool
	CreatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

type RolePermission struct {
	RoleID        pgtype.UUID
	PermissionKey string
}

type Session struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	TokenHash         []byte
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

type Setting struct {
	OrganizationID pgtype.UUID
	Key            string
	Value          string
	Version        int64
	UpdatedBy      pgtype.UUID
	UpdatedAt      pgtype.Timestamptz
}

type User struct {
	ID          pgtype.UUID
	Email       string
	DisplayName string
	Status      string
	CreatedAt   pgtype.Timestamptz
}
