// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID                      pgtype.UUID
	OrganizationID          pgtype.UUID
	OccurredAt              pgtype.Timestamptz
	ActorType               string
	ActorUserID             pgtype.UUID
	ActorService            *string
	Action                  string
	TargetType              string
	TargetID                *string
	Outcome                 string
	PreviousState           *string
	NextState               *string
	PayloadDigest           []byte
	PayloadDigestKeyVersion *int32
	RequestID               *string
	ConnectionID            pgtype.UUID
	QueryType               *string
	RowsAffected            *int64
	DurationMs              *int64
	RiskScore               *float64
	Metadata                []byte
}

type AuthMethod struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Type      string
	Secret    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type OidcIdentity struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Issuer    string
	Subject   string
	Email     string
	CreatedAt pgtype.Timestamptz
}

type Organization struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
}

type OrganizationMembership struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	RoleID         pgtype.UUID
}

type Permission struct {
	Key         string
	Description string
}

type Role struct {
	ID                 pgtype.UUID
	OrganizationID     pgtype.UUID
	Name               string
	IsSystem           bool
	IsBootstrapDefault bool
	CreatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

type RolePermission struct {
	RoleID        pgtype.UUID
	PermissionKey string
}

type Session struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	TokenHash         []byte
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

type User struct {
	ID          pgtype.UUID
	Email       string
	DisplayName string
	Status      string
	CreatedAt   pgtype.Timestamptz
}
