// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oidc.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findUserBySubject = `-- name: FindUserBySubject :one
select u.id, u.email, u.display_name, u.status, u.created_at
from oidc_identities i
join users u on u.id = i.user_id
where i.issuer = $1 and i.subject = $2
`

type FindUserBySubjectParams struct {
	Issuer  string
	Subject string
}

func (q *Queries) FindUserBySubject(ctx context.Context, arg FindUserBySubjectParams) (User, error) {
	row := q.db.QueryRow(ctx, findUserBySubject, arg.Issuer, arg.Subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const linkOIDCIdentity = `-- name: LinkOIDCIdentity :exec
insert into oidc_identities (user_id, issuer, subject, email)
values ($1, $2, $3, $4)
on conflict (issuer, subject) do nothing
`

type LinkOIDCIdentityParams struct {
	UserID  pgtype.UUID
	Issuer  string
	Subject string
	Email   string
}

func (q *Queries) LinkOIDCIdentity(ctx context.Context, arg LinkOIDCIdentityParams) error {
	_, err := q.db.Exec(ctx, linkOIDCIdentity,
		arg.UserID,
		arg.Issuer,
		arg.Subject,
		arg.Email,
	)
	return err
}
