// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (OrganizationMembership, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetDefaultOrganization(ctx context.Context) (Organization, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (OrganizationMembership, error)
	GetPasswordAuth(ctx context.Context, userID pgtype.UUID) (AuthMethod, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	RevokeSession(ctx context.Context, id pgtype.UUID) error
	UpsertPasswordAuth(ctx context.Context, arg UpsertPasswordAuthParams) error
}

var _ Querier = (*Queries)(nil)
