// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BootstrapRoleID(ctx context.Context, organizationID pgtype.UUID) (pgtype.UUID, error)
	// Total matching rows for the page controls. O(n) on a large table — PRD §7.1
	// accepts this for the audit list and defers keyset pagination to "later".
	CountAuditEvents(ctx context.Context, organizationID pgtype.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (OrganizationMembership, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Slide the idle window forward on activity, never past the absolute expiry and
	// never backward (greatest() guards against a late, older request regressing it).
	// Re-check both expiries in the write: a session can expire after Authenticate
	// reads it but before the post-CSRF slide, and an expired session must never be
	// resurrected by that race.
	ExtendSessionIdle(ctx context.Context, arg ExtendSessionIdleParams) error
	FindUserBySubject(ctx context.Context, arg FindUserBySubjectParams) (User, error)
	GetDefaultOrganization(ctx context.Context) (Organization, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (OrganizationMembership, error)
	GetPasswordAuth(ctx context.Context, userID pgtype.UUID) (AuthMethod, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	// User + password hash in one round-trip, so a password login costs the same
	// number of queries whether or not the account exists (anti-enumeration). The
	// hash is empty for OIDC-only users (no password row).
	GetUserForLogin(ctx context.Context, lower string) (GetUserForLoginRow, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error
	// Idempotent only for the same user: a new (issuer, subject) inserts; an
	// existing one owned by the same user refreshes the email; one owned by a
	// different user matches the conflict but fails the WHERE, so no row is
	// returned and the caller detects the collision (vs. silently succeeding).
	LinkOIDCIdentity(ctx context.Context, arg LinkOIDCIdentityParams) (pgtype.UUID, error)
	// Oldest first; (occurred_at asc, id asc) is the same index scanned backward, so it
	// stays index-served and tie-breaker-stable.
	ListAuditEventsAsc(ctx context.Context, arg ListAuditEventsAscParams) ([]ListAuditEventsAscRow, error)
	// Newest first, org-scoped; ordered by (occurred_at desc, id desc) to match the
	// audit_events_org_time_idx covering index (forward scan) and give OFFSET
	// pagination a stable tie-breaker (PRD §7.1). Extended columns
	// (state/execution/digest) are omitted until the features that populate them ship.
	ListAuditEventsDesc(ctx context.Context, arg ListAuditEventsDescParams) ([]ListAuditEventsDescRow, error)
	ListPermissionKeys(ctx context.Context) ([]string, error)
	// A user's effective permissions within one organization. Scoped by org (ADR-0004
	// repository contract) and joined to roles so a soft-deleted role stops granting
	// its permissions even while a membership still references it (FKs are RESTRICT).
	PermissionsForUser(ctx context.Context, arg PermissionsForUserParams) ([]string, error)
	// Only an ACTIVE session revokes: re-revoking (a concurrent double logout) must
	// not overwrite the original revoked_at — forensic evidence of WHEN the session
	// actually died — and the caller skips the audit event when no row changed, so
	// the trail records only real state changes (ADR-0009).
	RevokeSession(ctx context.Context, id pgtype.UUID) (int64, error)
	// Invalidate a user's active sessions (ADR-0006: login/privilege change rotates).
	RevokeUserSessions(ctx context.Context, userID pgtype.UUID) error
	UpsertPasswordAuth(ctx context.Context, arg UpsertPasswordAuthParams) error
}

var _ Querier = (*Queries)(nil)
