// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bootstrapRoleID = `-- name: BootstrapRoleID :one
select id from roles
where organization_id = $1 and is_bootstrap_default and deleted_at is null
limit 1
`

func (q *Queries) BootstrapRoleID(ctx context.Context, organizationID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, bootstrapRoleID, organizationID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listPermissionKeys = `-- name: ListPermissionKeys :many
select key from permissions order by key
`

func (q *Queries) ListPermissionKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permissionsForUser = `-- name: PermissionsForUser :many
select distinct rp.permission_key
from organization_memberships m
join roles r on r.id = m.role_id and r.deleted_at is null
join role_permissions rp on rp.role_id = m.role_id
where m.organization_id = $1 and m.user_id = $2
`

type PermissionsForUserParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
}

// A user's effective permissions within one organization. Scoped by org (ADR-0004
// repository contract) and joined to roles so a soft-deleted role stops granting
// its permissions even while a membership still references it (FKs are RESTRICT).
func (q *Queries) PermissionsForUser(ctx context.Context, arg PermissionsForUserParams) ([]string, error) {
	rows, err := q.db.Query(ctx, permissionsForUser, arg.OrganizationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission_key string
		if err := rows.Scan(&permission_key); err != nil {
			return nil, err
		}
		items = append(items, permission_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
