import { expect, test } from "@playwright/test";

import { signInForScenario } from "@e2e/login";
import { loadTarget } from "@e2e/target";

test("approved SQL executes once, pages and sorts exact values, filters and exports CSV", async ({ page, context }) => {
  await context.grantPermissions(["clipboard-read", "clipboard-write"]);
  let executionCalls = 0;
  page.on("request", request => { if (request.url().endsWith(".QueryExecutions/Execute")) executionCalls++; });
  await page.goto("/login");
  await signInForScenario(page, "admin@example.com", "correct-horse-battery");
  const target = await loadTarget();
  await page.getByRole("button", { name: "New connection" }).click();
  await page.getByLabel("Display name").fill("ExecutionTarget");
  await page.getByLabel("Host").fill(target.host);
  await page.getByLabel("Port").fill(String(target.port));
  await page.getByLabel("Database").fill(target.database);
  await page.getByLabel("User").fill(target.user);
  await page.getByLabel("Password", { exact: true }).fill(target.password);
  await page.getByLabel("TLS mode").selectOption("disable");
  await page.getByRole("button", { name: "Create", exact: true }).click();
  const connection = page.getByRole("row", { name: /ExecutionTarget/ });
  await connection.getByRole("button", { name: "Policy" }).click();
  await page.getByLabel("Read approvals").fill("0");
  await page.getByRole("button", { name: "Save policy" }).click();
  await expect(page.getByRole("button", { name: "Save policy" })).toHaveCount(0);
  await page.getByRole("link", { name: /Requests/ }).click();
  await page.getByRole("button", { name: "New request" }).click();
  await page.getByLabel("Connection").selectOption({ label: "ExecutionTarget" });
  await page.getByLabel("Title", { exact: true }).fill("Query review");
  await page.getByLabel("SQL", { exact: true }).fill("SELECT (9007199254740993::bigint + g) AS exact_value, '=formula'::text AS note, CASE WHEN g % 2 = 0 THEN '2026-10-03T00:00:00Z'::timestamptz ELSE '2026-10-03T00:00:00.5Z'::timestamptz END AS recorded_at FROM generate_series(1,25) AS g ORDER BY g ASC");
  await page.getByRole("button", { name: "Submit", exact: true }).click();
  const row = page.getByRole("region", { name: "Request details" });
  await expect(row.getByText("Approved", { exact: true })).toBeVisible();
  await row.getByRole("button", { name: "Execute", exact: true }).click();
  await expect(row.getByText("Succeeded", { exact: true })).toBeVisible();
  await expect(row.getByRole("button", { name: "Execute", exact: true })).toHaveCount(0);
  const executionSummary = row.getByRole("region", { name: "Execution summary", exact: true });
  await expect(executionSummary.getByText("Execution time", { exact: true })).toBeVisible();
  const duration = executionSummary.getByLabel("Recorded execution time", { exact: true });
  await expect(duration).toHaveText(/^(?:<1 ms|\d+ ms|\d+\.\d{3} s)$/);
  const recordedDuration = await duration.textContent();
  await page.reload();
  await expect(row.getByLabel("Recorded execution time", { exact: true })).toHaveText(recordedDuration!);
  await row.getByRole("link", { name: "Result", exact: true }).click();
  await expect(page).toHaveURL(/\/requests\/[0-9a-f-]+\/result$/);
  await expect(page.getByRole("dialog")).toHaveCount(0);
  const dialog = page.getByRole("region", { name: "Query results" });
  await expect(dialog.getByLabel("Recorded execution time", { exact: true })).toHaveText(recordedDuration!);
  await expect(dialog.getByText("9007199254740994", { exact: true })).toBeVisible();
  await dialog.getByRole("button", { name: "Next page", exact: true }).click();
  await expect(dialog.getByText("9007199254741018", { exact: true })).toBeVisible();
  await dialog.getByRole("button", { name: /exact_value/ }).click();
  await dialog.getByRole("button", { name: /exact_value/ }).click();
  await expect(dialog.getByRole("row").nth(1)).toContainText("9007199254741018");
  await expect(dialog.getByRole("columnheader", { name: /exact_value/ })).toHaveAttribute("aria-sort", "descending");
  await expect(dialog.getByText(/25 rows · Page 1 of 2/)).toBeVisible();
  await dialog.getByRole("button", { name: /exact_value/ }).click();
  await expect(dialog.getByText("Original query order.", { exact: true })).toBeVisible();
  await expect(dialog.getByRole("row").nth(1)).toContainText("9007199254740994");
  await expect(dialog.getByRole("columnheader", { name: /exact_value/ })).not.toHaveAttribute("aria-sort");
  await dialog.getByLabel("Sort by", { exact: true }).selectOption("2");
  await expect(dialog.getByRole("columnheader", { name: /recorded_at/ })).toHaveAttribute("aria-sort", "ascending");
  await expect(dialog.getByRole("row").nth(1)).toContainText("9007199254740995");
  await dialog.getByLabel("Sort direction", { exact: true }).selectOption("descending");
  await expect(dialog.getByRole("columnheader", { name: /recorded_at/ })).toHaveAttribute("aria-sort", "descending");
  await expect(dialog.getByRole("row").nth(1)).toContainText("9007199254740994");
  await test.info().attach("Type-aware result sorting", { body: await page.screenshot({ fullPage: true }), contentType: "image/png" });
  await dialog.getByRole("button", { name: "Restore query order", exact: true }).click();
  await expect(dialog.getByText("Original query order.", { exact: true })).toBeVisible();
  await dialog.getByLabel("Filter results", { exact: true }).fill("9007199254740994");
  await dialog.getByRole("button", { name: "Filter results", exact: true }).click();
  await expect(dialog.getByText(/1 rows · Page 1 of 1/)).toBeVisible();
  await dialog.getByLabel("Sort by", { exact: true }).selectOption("0");
  await expect(dialog.getByRole("columnheader", { name: /exact_value/ })).toHaveAttribute("aria-sort", "ascending");
  await dialog.getByRole("button", { name: "Restore query order", exact: true }).click();
  await expect(dialog.getByText(/1 rows · Page 1 of 1/)).toBeVisible();
  await dialog.getByRole("button", { name: "Text", exact: true }).click();
  await expect(dialog.getByLabel("Text results")).toContainText("9007199254740994\t=formula");
  await expect(dialog.getByLabel("Text results")).not.toContainText("9007199254741018");
  await dialog.getByRole("button", { name: "Copy visible rows", exact: true }).click();
  await expect(dialog.getByText("Copied 1 visible rows with column headers.")).toBeVisible();
  const copied = await page.evaluate(() => navigator.clipboard.readText());
  expect(copied).toContain("exact_value\tnote\trecorded_at");
  expect(copied).toContain("9007199254740994\t'=formula");
  expect(copied).not.toContain("9007199254741018");
  await page.evaluate(() => Object.defineProperty(navigator.clipboard, "writeText", {
    configurable: true, value: async () => { throw new DOMException("Denied", "NotAllowedError"); },
  }));
  await dialog.getByRole("button", { name: "Copy visible rows", exact: true }).click();
  await expect(dialog.getByText(/Clipboard access was denied or unavailable/)).toBeVisible();
  await dialog.getByRole("button", { name: "Table", exact: true }).click();
  await expect(dialog.getByRole("row").nth(1)).toContainText("9007199254740994");
  await dialog.getByRole("button", { name: "Export CSV", exact: true }).click();
  const downloadLink = dialog.getByRole("link", { name: "Download CSV", exact: true });
  await expect(downloadLink).toBeVisible();
  // The saved download is read back below; the page itself may not fetch its blob: URL because connect-src admits only the SPA origin.
  const download = page.waitForEvent("download");
  await downloadLink.click();
  const csv = await download;
  expect(csv.suggestedFilename()).toBe("query-result.csv");
  expect(await csv.failure()).toBeNull();
  const csvStream = await csv.createReadStream();
  expect(csvStream).not.toBeNull();
  let contents = "";
  if (csvStream) for await (const chunk of csvStream) contents += String(chunk);
  expect(contents).toContain("9007199254740994,'=formula");
  expect(contents).toContain("9007199254741018,'=formula");
  expect(contents.indexOf("9007199254740994,'=formula")).toBeLessThan(contents.indexOf("9007199254741018,'=formula"));
  expect(executionCalls).toBe(1);
});
