import { expect, test } from "@playwright/test";
import { loadTarget } from "@e2e/target";

test("approved SQL executes once, pages and sorts exact values, filters and exports CSV", async ({ page }) => {
  await page.goto("/login");
  await page.getByLabel("Email").fill("admin@example.com");
  await page.getByLabel("Password", { exact: true }).fill("correct-horse-battery");
  await page.getByRole("button", { name: "Sign in" }).click();
  await expect(page).toHaveURL(/\/connections$/);
  const target = await loadTarget();
  await page.getByRole("button", { name: "New connection" }).click();
  await page.getByLabel("Display name").fill("ExecutionTarget");
  await page.getByLabel("Host").fill(target.host);
  await page.getByLabel("Port").fill(String(target.port));
  await page.getByLabel("Database").fill(target.database);
  await page.getByLabel("User").fill(target.user);
  await page.getByLabel("Password", { exact: true }).fill(target.password);
  await page.getByLabel("TLS mode").selectOption("disable");
  await page.getByRole("button", { name: "Create", exact: true }).click();
  const connection = page.getByRole("row", { name: /ExecutionTarget/ });
  await connection.getByRole("button", { name: "Policy" }).click();
  await page.getByLabel("Read approvals").fill("0");
  await page.getByRole("button", { name: "Save policy" }).click();
  await expect(page.getByRole("button", { name: "Save policy" })).toHaveCount(0);
  await page.getByRole("link", { name: /Requests/ }).click();
  await page.getByRole("button", { name: "New request" }).click();
  await page.getByLabel("Connection").selectOption({ label: "ExecutionTarget" });
  await page.getByLabel("SQL").fill("SELECT (9007199254740993::bigint + g) AS exact_value, '=formula'::text AS note FROM generate_series(1,25) AS g");
  await page.getByRole("button", { name: "Submit", exact: true }).click();
  const row = page.getByRole("region", { name: "Request details" });
  await expect(row.getByText("Approved", { exact: true })).toBeVisible();
  await row.getByRole("button", { name: "Execute", exact: true }).click();
  await expect(row.getByText("Succeeded", { exact: true })).toBeVisible();
  await expect(row.getByRole("button", { name: "Execute", exact: true })).toHaveCount(0);
  await row.getByRole("link", { name: "Result", exact: true }).click();
  await expect(page).toHaveURL(/\/requests\/[0-9a-f-]+\/result$/);
  await expect(page.getByRole("dialog")).toHaveCount(0);
  const dialog = page.getByRole("region", { name: "Query results" });
  await expect(dialog.getByText("9007199254740994", { exact: true })).toBeVisible();
  await dialog.getByRole("button", { name: "Next page", exact: true }).click();
  await expect(dialog.getByText("9007199254741018", { exact: true })).toBeVisible();
  await dialog.getByRole("button", { name: /exact_value/ }).click();
  await dialog.getByRole("button", { name: /exact_value/ }).click();
  await expect(dialog.getByRole("row").nth(1)).toContainText("9007199254741018");
  await dialog.getByLabel("Filter results", { exact: true }).fill("9007199254740994");
  await dialog.getByRole("button", { name: "Filter results", exact: true }).click();
  await expect(dialog.getByText(/1 rows · Page 1 of 1/)).toBeVisible();
  await dialog.getByRole("button", { name: "Export CSV", exact: true }).click();
  const downloadLink = dialog.getByRole("link", { name: "Download CSV", exact: true });
  await expect(downloadLink).toBeVisible();
  const prepared = await downloadLink.evaluate(async link => (await fetch((link as HTMLAnchorElement).href)).text());
  expect(prepared).toContain("9007199254740994,'=formula");
  expect(prepared).toContain("9007199254741018,'=formula");
  const download = page.waitForEvent("download");
  await downloadLink.click();
  const csv = await download;
  expect(csv.suggestedFilename()).toBe("query-result.csv");
  expect(await csv.failure()).toBeNull();
  const csvStream = await csv.createReadStream();
  expect(csvStream).not.toBeNull();
  let contents = "";
  if (csvStream) for await (const chunk of csvStream) contents += String(chunk);
  expect(contents).toContain("9007199254740994,'=formula");
  expect(contents).toContain("9007199254741018,'=formula");
});
