// Package connection defines target descriptors, TLS policy, and sealed credentials.
package connection

// ConnectionID identifies one registered connection. It is generated by the application (not a database default) because the credential envelope's AAD binds the record id before the row exists (ADR-0003, ADR-0014).
type ConnectionID string
