// Package connection is the target-database bounded context: registered
// database connections, their validated targets and TLS posture, and the
// sealed credential that authenticates to them. It holds entities, value
// objects, repository ports, and pure domain rules — no infrastructure. Each
// concept lives in its own file (connection.go, target.go, tlsmode.go,
// credential.go); this file keeps only the cross-concept vocabulary.
package connection

// ConnectionID identifies one registered connection. It is generated by the
// application (not a database default) because the credential envelope's AAD
// binds the record id before the row exists (ADR-0003, ADR-0014).
type ConnectionID string
